### ISSUE TITLE
Values in cds-hook Suggestion response

### ISSUE THREAD

**Issue by xmlmodeling** [DBCG/cqf-ruler#11]
First, I want to say Thank You for this awesome framework and service for CQL and cds-hooks, it will be a huge benefit for me to learn CQL and develop/test cds-hook services using PlanDefinition!

I installed the server and am testing examples from cds-quality-summit.  Comparing with cds-hooks spec, the Suggestion response appears to contain two errors:
* the "type" value should be lower case, "create" instead of "CREATE"
* As copied below from a response, the actions "resource" value is serialized into a string. This should be a Resource object, not a string?? 

      "suggestions": [
        {
          "actions": [
            {
              "type": "CREATE",
              "resource": "{\n  \"resourceType\": \"ProcedureRequest\",\n  \"status\": \"draft\",\n  \"intent\": \"order\",\n  \"code\": {\n    \"coding\": [\n      {\n        \"system\": \"http://www.ama-assn.org/go/cpt\",\n        \"code\": \"82272\",\n        \"display\": \"Fecal Occult Blood Test\"\n      }\n    ]\n  },\n  \"subject\": {\n    \"reference\": \"Patient/Patient-276\"\n  }\n}"
            }
          ]

Thanks!
  Dave Carlson

**Comment by c-schuler** [comment]
Hi Dave,
Thanks for the kind words. You're absolutely right about these issues. Not sure how I got it so mixed up =). Fix coming.

**Comment by xmlmodeling** [comment]
Hi Chris,
Thanks for your quick reply.  I have additional thoughts about generalizing the support for cds-hook services.  I'll get a dev environment set up soon and try to submit a PR.  Getting ready for a trip to Amsterdam to attend FHIR DevDays next week.  Will you be there?  I intend to chat with Bryn about this server and integrating with the HSPC sandbox

Dave

**Comment by c-schuler** [comment]
That's great Dave! Unfortunately, I won't be attending FHIR DevDays. I look forward to collaborating with you and am excited about integrating with the sandbox.
Thanks Dave!

**Comment by xmlmodeling** [comment]
Thanks Chris, I tested your update and it's now working.  However, I am not
getting results as expected when invoking the cds-hooks service.  Where is
the best channel to ask these kinds of questions for cqf-ruler?

I am invoking col-decision-support via cds-hooks using the example
request.json provided in the repo.  I get 4 cards in return.  The first
condition for patient qualification is that age must be between 51 and 75.
I updated Patient-276 resource on the server with birthdate as 1970 instead
of 1960, which should disqualify the patient from all other actions in this
CDS service.  But I still get the same 4 cards and recommendations in
response.  I should get no cards, correct?  Not sure how to debug this.

As I work through this CDS development process, my understanding is that
the 'col-plandefinition-logic.cql' is converted to ELM, serialized to
base-64 and included in the Library.content element. So in
'col-library.json' for this example.  Correct?  Could it be that this
content is not correct or current?  What tooling or workflow can you
recommend for updating these artifacts?

Thanks!
  Dave Carlson
  dcarlson@xmlmodeling.com

Thank you,
  Dave Carlson, MBA, Ph.D.
  email: dcarlson@ClinicalCloud.solutions
  Clinical Cloud Solutions LLC, healthcare on HL7 FHIR
  http://www.ClinicalCloud.solutions

**Comment by c-schuler** [comment]
Hey Dave,

Ah, yes I see what's happening. The data provider is set to http://measure.eval.kanvix.com/cqf-ruler/baseDstu3 [here](http://measure.eval.kanvix.com/cqf-ruler/baseDstu3). Change that to point to your local instance. I should come up with a strategy to set that dynamically...

Do you have a [fhir chat account](https://chat.fhir.org)? If not, create an account and join the CQL stream. You can ask questions there or you may also message me directly at cschuler@myharmoniq.com.

You're correct about the CDS development process. The workflow consists of using the [cql-to-elm translator](https://github.com/cqframework/clinical_quality_language/tree/master/Src/java) to get the ELM, then encode as base64, then author the library resource and attach content. We are working on tooling to automate this process, but it isn't publicly available yet.

Hope that helps!

Thanks,
Chris

**Comment by c-schuler** [comment]
Closing this.
