### ISSUE TITLE
Support for $collect-data

### ISSUE THREAD

**Issue by mgramigna** [DBCG/cqf-ruler#110]
cqf-ruler does not currently support the [$collect-data operation](http://hl7.org/fhir/2018Sep/measure-operation-collect-data.html). Is support for this operation planned in the near future?

Thanks

**Comment by c-schuler** [comment]
Hi @mgramigna, yes, support for the $collect-data operation is pending and should be implemented within the week.

**Comment by JPercival** [comment]
Resolved by #110
