### ISSUE TITLE
Issue with including libraries inside main library cql

### ISSUE THREAD

**Issue by sg11pankaj** [DBCG/cqf-ruler#111]
Hi-

Can you help in identifying the issue here? 
[test-PA-usecase.zip](https://github.com/DBCG/cqf-ruler/files/3086208/test-PA-usecase.zip)
I'm using attach libraries and bundle for my use case but those are ingested to the server but give below error during loadLibrary or translate CQLtoELM.

ERRORs:
========================================================================================
>> Translation Error: [Test-PA-1[7:1, 7:63]Cannot find library source CDSConnectCommonsforFHIRv300
, Test-PA-1[9:1, 9:56]Cannot find library source CDSConnectConversions
, Test-PA-1[50:14, 50:82]Could not resolve library name C3F.
, Test-PA-1[53:28, 53:83]Could not resolve library name C3F.
, Test-PA-1[56:28, 56:83]Could not resolve library name C3F.
, Test-PA-1[59:34, 59:83]Could not resolve library name C3F.
, Test-PA-1[62:28, 62:82]Could not resolve library name C3F.
, Test-PA-1[65:28, 65:83]Could not resolve library name C3F.
, Test-PA-1[74:3, 74:20]Could not validate reference to expression Cancer condition because its definition contains errors.
, Test-PA-1[68:3, 68:16]Could not validate reference to expression Known Cancer because its definition contains errors.
, Test-PA-1[78:3, 78:11]Could not validate reference to expression XR Knee because its definition contains errors.
, Test-PA-1[82:3, 82:20]Could not validate reference to expression SNOMED 397758007 because its definition contains errors.
, Test-PA-1[86:3, 86:20]Could not validate reference to expression Patella Fracture because its definition contains errors.
, Test-PA-1[90:3, 90:13]Could not validate reference to expression infection because its definition contains errors.
, Test-PA-1[94:4, 94:27]Could not validate reference to expression MeetsInclusionCriteria because its definition contains errors.
, Test-PA-1[97:6, 97:19]Could not validate reference to expression InPopulation because its definition contains errors.
, Test-PA-1[101:6, 101:19]Could not validate reference to expression InPopulation because its definition contains errors.
, Test-PA-1[107:6, 107:19]Could not validate reference to expression Known Cancer because its definition contains errors.
]

I get an error on translating CQLtoELM when the engine tries to load and translate library during execution if I include all functions in a single library from different libraries I was trying to use.

Exception:
========================================================================================
>>java.lang.IllegalArgumentException: [Test-PA-1[5:1, 5:54]Could not load source for library FHIRHelpers, version 3.0.0., Test-PA-1[179:10, 179:37]Could not resolve library name FHIRHelpers., Test-PA-1[177:11, 179:37]Could not determine signature for invocation of operator System.Or., Test-PA-1[177:5, 179:37]Expected an expression of type 'System.Boolean', but found an expression of type '<unknown>'., Test-PA-1[110:39, 110:52]Could not resolve library name FHIRHelpers., Test-PA-1[110:3, 110:62]Expected an expression of type '<unknown>', but found an expression of type 'System.Any'., Test-PA-1[110:39, 110:52]Could not resolve library name FHIRHelpers., Test-PA-1[110:3, 110:62]Expected an expression of type '<unknown>', but found an expression of type 'System.Any'., Test-PA-1[144:25, 144:49]Could not resolve call to operator NullSafeToConcept with signature (FHIR.CodeableConcept)., Test-PA-1[144:25, 144:59]Could not determine signature for invocation of operator System.Equivalent., Test-PA-1[144:19, 144:59]Expected an expression of type 'System.Boolean', but found an expression of type '<unknown>'., Test-PA-1[110:39, 110:52]Could not resolve library name FHIRHelpers., Test-PA-1[110:3, 110:62]Expected an expression of type '<unknown>', but found an expression of type 'System.Any'., Test-PA-1[206:3, 206:54]Could not resolve call to operator NullSafeToConcept with signature (FHIR.CodeableConcept)., Test-PA-1[110:39, 110:52]Could not resolve library name FHIRHelpers., Test-PA-1[110:3, 110:62]Expected an expression of type '<unknown>', but found an expression of type 'System.Any'., Test-PA-1[237:23, 237:47]Could not resolve call to operator NullSafeToConcept with signature (FHIR.CodeableConcept)., Test-PA-1[237:23, 237:57]Could not determine signature for invocation of operator System.Equivalent., Test-PA-1[237:17, 237:57]Expected an expression of type 'System.Boolean', but found an expression of type '<unknown>'., Test-PA-1[288:10, 288:43]Could not resolve library name FHIRHelpers., Test-PA-1[286:11, 288:43]Could not determine signature for invocation of operator System.Or., Test-PA-1[286:5, 288:43]Expected an expression of type 'System.Boolean', but found an expression of type '<unknown>'., Test-PA-1[110:39, 110:52]Could not resolve library name FHIRHelpers., Test-PA-1[110:3, 110:62]Expected an expression of type '<unknown>', but found an expression of type 'System.Any'., Test-PA-1[309:24, 309:48]Could not resolve call to operator NullSafeToConcept with signature (FHIR.CodeableConcept)., Test-PA-1[309:24, 309:58]Could not determine signature for invocation of operator System.Equivalent., Test-PA-1[309:18, 309:58]Expected an expression of type 'System.Boolean', but found an expression of type '<unknown>'., Test-PA-1[110:39, 110:52]Could not resolve library name FHIRHelpers., Test-PA-1[110:3, 110:62]Expected an expression of type '<unknown>', but found an expression of type 'System.Any'., Test-PA-1[369:33, 369:87]Could not resolve call to operator NullSafeToConcept with signature (FHIR.CodeableConcept)., Test-PA-1[369:33, 369:97]Could not determine signature for invocation of operator System.Equivalent., Test-PA-1[369:27, 369:97]Expected an expression of type 'System.Boolean', but found an expression of type '<unknown>'., Test-PA-1[110:39, 110:52]Could not resolve library name FHIRHelpers., Test-PA-1[110:3, 110:62]Expected an expression of type '<unknown>', but found an expression of type 'System.Any'., Test-PA-1[378:31, 378:85]Could not resolve call to operator NullSafeToConcept with signature (FHIR.CodeableConcept)., Test-PA-1[378:31, 378:95]Could not determine signature for invocation of operator System.Equivalent., Test-PA-1[378:25, 378:95]Expected an expression of type 'System.Boolean', but found an expression of type '<unknown>'., Test-PA-1[110:39, 110:52]Could not resolve library name FHIRHelpers., Test-PA-1[110:3, 110:62]Expected an expression of type '<unknown>', but found an expression of type 'System.Any'., Test-PA-1[459:49, 459:69]Could not resolve call to operator NullSafeToConcept with signature (FHIR.CodeableConcept)., Test-PA-1[459:49, 459:79]Could not determine signature for invocation of operator System.Equivalent., Test-PA-1[459:43, 459:79]Expected an expression of type 'System.Boolean', but found an expression of type '<unknown>'., Test-PA-1[110:39, 110:52]Could not resolve library name FHIRHelpers., Test-PA-1[110:3, 110:62]Expected an expression of type '<unknown>', but found an expression of type 'System.Any'., Test-PA-1[480:32, 480:56]Could not resolve call to operator NullSafeToConcept with signature (FHIR.CodeableConcept)., Test-PA-1[480:32, 480:66]Could not determine signature for invocation of operator System.Equivalent., Test-PA-1[480:26, 480:66]Expected an expression of type 'System.Boolean', but found an expression of type '<unknown>'.]
	at org.opencds.cqf.helpers.LibraryHelper.getTranslator(LibraryHelper.java:64)
	at org.opencds.cqf.helpers.LibraryHelper.translateLibrary(LibraryHelper.java:76)
	at org.opencds.cqf.config.STU3LibraryLoader.toElmLibrary(STU3LibraryLoader.java:74)
	at org.opencds.cqf.config.STU3LibraryLoader.loadLibrary(STU3LibraryLoader.java:85)
	at org.opencds.cqf.config.STU3LibraryLoader.resolveLibrary(STU3LibraryLoader.java:58)
	at org.opencds.cqf.config.STU3LibraryLoader.load(STU3LibraryLoader.java:116)
	at org.opencds.cqf.providers.FHIRPlanDefinitionResourceProvider.getDiscovery(FHIRPlanDefinitionResourceProvider.java:457)
	at org.opencds.cqf.cdshooks.providers.CdsHooksProviders.<init>(CdsHooksProviders.java:97)
	at org.opencds.cqf.servlet.CdsServicesServlet.doPost(CdsServicesServlet.java:36)
	at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1504)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)

**Comment by sg11pankaj** [comment]
1 issue I found is the way I've defined library name but I'm getting same exception even after the below correction :

>library "Test-PA" version '1' 

to 

>library TestPA version '1'

**Comment by sg11pankaj** [comment]
@c-schuler - Hi- Any update on this? Is this an issue, as I see similar root cause stacktrace for issue #112  or are we making a mistake somewhere?

**Comment by JPercival** [comment]
Closing this as stale. Feel free to reopen if it's stuff an issue.
