### ISSUE TITLE
Change contained resource packaging in $evaluate-measure

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cqf-ruler#147]
The current implementation of $evaluate-measure creates a Bundle for all the evaluated resources, and then includes that resource as the single evaluatedResource element for the MeasureReport, and includes that Bundle as a contained resource.

The MeasureReport shouldn't include things that way, the List resources are used to track the resources referenced during evaluation of each population, those List resources should be the only thing included as contained resources, and those should be referenced directly from the evaluatedResource element.

If a client wants to retrieve the evaluatedResources, they can with the List, but they don't have to be returned on every $evaluate, only references.

**Comment by JPercival** [comment]
Fixed in the CQL evaluator.
