### ISSUE TITLE
$collect-data operation calling `evaluateMeasure` incorrectly

### ISSUE THREAD

**Issue by Dranith** [DBCG/cqf-ruler#149]
In both the `r4` and `stu3` code, the `$collect-data` function calls `evaluateMeasure`.  It is passing the arguments an incorrect order.

Example (from [refactored-engine-dataprovider branch](https://github.com/DBCG/cqf-ruler/blob/refactored-engine-dataprovider/r4/src/main/java/org/opencds/cqf/r4/providers/MeasureOperationsProvider.java#L328) )
```
MeasureReport report = evaluateMeasure(
    theId, 
    periodStart, 
    periodEnd, 
    null, 
    null, 
    null,                    // <--- This is actually patientRef
    patientRef,          // <--- This is productLine
    practitionerRef, 
    lastReceivedOn, 
    null, 
    null, 
    null);
```

This isn't currently causing our team any issues, but noticed it while working with other parts of the code.

**Comment by JPercival** [comment]
Resolved in #155
