### ISSUE TITLE
Population evaluate fails due to expression caching issue

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cqf-ruler#153]
Expression caching is not being cleared, which results in incorrect population calculation results

See engine issue: https://github.com/DBCG/cql_engine/issues/273

Include a population test (at least two, use CMS130 numer and denom) from the DBCG Connectathon repository.

**Comment by brynrhodes** [comment]
Note that disabling the expression caching in the MeasureEvaluationSeed context creation doesn't work either (it gets re-enabled somewhere down the line).

**Comment by JPercival** [comment]
Fix merged into develop
