### ISSUE TITLE
Measures are not using population criteria id

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cqf-ruler#161]
The measures in the connectathon repo do not have the Measure.group.population.id element filled out, but that should be a required element.
Note though that the reference implementation should not fail without them, but if they are present, the implementation should be using the id to coordinate repsonses in a MeasureReport to the population criteria in the Measure (in addition to the code).

**Comment by rob-reynolds** [comment]
Updated cqf-ruler so the elements are filled-out for stu3 MeasureReports.

**Comment by rob-reynolds** [comment]
Moving the content issue to the Connectathon repo.
