### ISSUE TITLE
ReportType should be "subject-list" not "patient-list" in $evaluate-measure

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cqf-ruler#170]
The CQF Ruler R4 implementation still uses "patient-list" not "subject-list":

http://cqm-sandbox.alphora.com/cqf-ruler-r4/fhir/Measure/measure-EXM130-FHIR4-7.2.000/$evaluate-measure?reportType=patient-list&periodStart=2019-01-01&periodEnd=2019-12-31

**Comment by brynrhodes** [comment]
It also appears to be using `patient` rather than `subject` as the name of the parameter

**Comment by brynrhodes** [comment]
Yes, at least in the main branch: https://github.com/DBCG/cqf-ruler/blob/master/r4/src/main/java/org/opencds/cqf/r4/providers/MeasureOperationsProvider.java#L186

**Comment by brynrhodes** [comment]
Note that `patient` and `patient-list` are correct for STU3. This issue only applies to R4.

**Comment by JPercival** [comment]
Resolved by #451
