### ISSUE TITLE
cqf-ruler user interface broken in develop branch

### ISSUE THREAD

**Issue by mattStorer** [DBCG/cqf-ruler#172]
the cqf-ruler UI is not rendering correctly, with apparently broken JavaScript and CSS links.

git-log shows most recent commit is c7d14ce1fad66ee7c6f06fdfd3d4983d77776b88:

> $ git log
> commit c7d14ce1fad66ee7c6f06fdfd3d4983d77776b88 (HEAD -> develop, origin/develop)
> Merge: b15350c 2a9f6c2
> Author: JPercival <JPercival@users.noreply.github.com>
> Date:   Sat Feb 8 01:37:49 2020 -0700

![image](https://user-images.githubusercontent.com/979938/74569328-038f4680-4f2f-11ea-81d4-9182b534f2b0.png)

OS is Windows 10 Enterprise version 1803 w/ OS build 17134.1246.
Java version is OpenJDK 11.0.6 w/ OpenJ9 VM
Browser is Google Chrome 80.0.3987.106.  Also tested on IE 11 v11.1246.17134.0 with same results.

**Comment by JPercival** [comment]
That is resolved on the develop branch of the ruler.
