### ISSUE TITLE
resources not refreshing until after cqf-ruler restart

### ISSUE THREAD

**Issue by mattStorer** [DBCG/cqf-ruler#173]
after cloning cqf-ruler and switching to the develop branch (most recent commit: c7d14ce1fad66ee7c6f06fdfd3d4983d77776b88), cqf-ruler-dstu3 is not reflecting newly-installed resources until after cqf-ruler is restarted.

> commit c7d14ce1fad66ee7c6f06fdfd3d4983d77776b88 (HEAD -> develop, origin/develop)
> Merge: b15350c 2a9f6c2
> Author: JPercival <JPercival@users.noreply.github.com>
> Date:   Sat Feb 8 01:37:49 2020 -0700

after posting new terminology and content bundles to cqf-ruler via Postman (per instructions at http://build.fhir.org/ig/cqframework/opioid-cds/quick-start.html), and after receiving good/expected 201 (created) responses for all items in Postman, refreshing the cqf-ruler UI does not show the number of resources beside each resource category (expect to see "ValueSet (19)" up at the top of the Resources list for example, but only seeing "ValueSet" down at the bottom until after a cqf-ruler restart).

I would post screenshots, but https://github.com/DBCG/cqf-ruler/issues/172 is preventing other parts of the UI from functioning at all so probably best to handle that bug first.

OS is Windows 10 Enterprise version 1803 w/ OS build 17134.1246.
Java version is OpenJDK 11.0.6 w/ OpenJ9 VM
Browser is Google Chrome 80.0.3987.106. Also tested on IE 11 v11.1246.17134.0 with same results.

**Comment by JPercival** [comment]
cqf-ruler is based on the HAPI FHIR server upstream. HAPI implements the resource counts via an indexing service that runs periodically. There can be a significant delay between the time a resource is added and the time the count is updated. The default is updating every 10 minutes.
