### ISSUE TITLE
Issue with Period and/or Interval

### ISSUE THREAD

**Issue by SeanWheelwright** [DBCG/cqf-ruler#187]
This works:
	FHIRHelpers.ToInterval(Colonoscopy.performed as FHIR.Period) ends 10 years or less on or before end of "Measurement Period"
	and this doesn't:
	Global."Normalize Onset"(Colonoscopy.performed) ends 10 years or less on or before end of "Measurement Period"
	define function 
	"Normalize Onset"(onset Choice<FHIR.dateTime, FHIR.Age, FHIR.Period, FHIR.Range, FHIR.string>):   if onset is FHIR.dateTime then Interval[onset.value, onset.value] 	else if onset is FHIR.Period then FHIRHelpers.ToInterval(onset as FHIR.Period) 	else null
Repro: reference Connectathon/master/EXM130 R4 cql

**Comment by JPercival** [comment]
This is actually an cql-engine issue. 130 R4 is currently running.
