### ISSUE TITLE
understanding the architecture flow

### ISSUE THREAD

**Issue by jigneshmpatel** [DBCG/cqf-ruler#209]
I have tried to compile cqf-ruler and I have few questions to understand about to generate a complete measure.
Just to understand high level structure, is it true that, cqf-ruler internally uses cql-engine and cql-elm files?
Moreover I could run using docker there I have even see that it internally uses derby database with HAPI FHIR?
What is the difference between cqf-ruler-r4 and only r4?
Do we need to integrate that with cql-runner?

**Comment by brynrhodes** [comment]
Hi Jignesh,

Yes, the CQFRuler uses a CQLEngine running internally to evaluate CQL. The CQFRuler is a set of ResourceProvider implementations that implement functions like $cql, $evaluate-measure, and $submit-data.

The docker has a default configuration, yes, but the configuration can be changed, and we include the docker files so you can create custom docker configurations if you need to.

The cqf-ruler-r4 is the servlet that runs the FHIR R4 server, while the r4 project folder contains r4 code.

No there is no need to integrate with the cql-runner, though if you have a running CQFRuler, the CQL-Runner can access it.

Hopefully this helps?

**Comment by jigneshmpatel** [comment]
Bryn,
Is there an architecture document for the CQFRuler?
What is the purpose of CQL-runner? 
What is the purpose of fhir-bulk-proxy project?
For us to import data from our database to CQFRuler- do we need to import in the format described in Denominator Test Bundle and Numerator Test Bundle? Why the sample for denominator and numerator are separate? Is there a guideline on how to use them?

**Comment by JPercival** [comment]
Lots of new documentation here:

https://github.com/DBCG/cqf-ruler/wiki/Architecture
