### ISSUE TITLE
can't run the project

### ISSUE THREAD

**Issue by jigneshmpatel** [DBCG/cqf-ruler#212]
mvn jetty:run -am --projects cqf-ruler-r4
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: cqf-ruler-r4 @ 
[ERROR] Could not find the selected project in the reactor: cqf-ruler-r4 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
 cqf-ruler-r4 % mvn jetty:run -am --projects cqf-ruler-r4
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM org.opencds.cqf:cqf-ruler-r4:${revision} (/cqf-ruler-r4/pom.xml) points at org.example:cqf-ruler instead of org.opencds.cqf:parent, please verify your project structure @ line 4, column 13
[FATAL] Non-resolvable parent POM for org.opencds.cqf:cqf-ruler-r4:${revision}: Failure to find org.opencds.cqf:parent:pom:${revision} in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 4, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.opencds.cqf:cqf-ruler-r4:${revision} (/Users/jigneshpatel/development/cqf-ruler/cqf-ruler-r4/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.opencds.cqf:cqf-ruler-r4:${revision}: Failure to find org.opencds.cqf:parent:pom:${revision} in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 4, column 13 -> [Help 2]

I am getting same error for JDK 8 and JDK 11? AmI suppose to run the program in JDK 11?

**Comment by brynrhodes** [comment]
Yes, the project requires Java11, we typically use OpenJDK11 and OpenJP: https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=openj9
I just did a fresh clone and ran the mvn jetty:run -am --projects cqf-ruler-r4 and it worked.
Are you also running at least Maven 3.5.3?

**Comment by JPercival** [comment]
The is error is caused by a version of maven that does not support the "revision" parameter.
