### ISSUE TITLE
CQF-Rular Database Connection.

### ISSUE THREAD

**Issue by jmistry65** [DBCG/cqf-ruler#219]
Hi,
I  would like to know with how many data base can be connect cqf ruler.
I am able to connect with MySql. Can we connect it with non relational Db?
If yes please let me know how.
Thanks

**Comment by JPercival** [comment]
The cqf-ruler is built as plugins to the HAPI FHIR server. Under the covers Hibernate is used so the server can be configured to talk to any database that hibernate can. Documentation is [here](https://hapifhir.io/hapi-fhir/docs/server_jpa/architecture.html).
