### ISSUE TITLE
Opioid "Triple Threat" Detection

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#22]
Concurrent use of three types of medications – opioids, benzodiazepines and muscle relaxants – called the “Triple Threat,” puts patients at a significant risk for overdose and death. This is probably out of scope right now for this hook, but its an important use case to consider for the future.

There is currently Rx data on http://54.165.182.195:8080 for patient Terry Zavala (Patient-6497) for  Xanax and Flexeril and we will use it in the upcoming hackathon.

**Comment by c-schuler** [comment]
We will be adding logic in the near future for recommendation 11 found [here](https://guidelines.gov/summaries/summary/50153/cdc-guideline-for-prescribing-opioids-for-chronic-pain---united-states-2016#420). It doesn't mention muscle relaxants... Is this the same use case as the "Triple Threat"?

**Comment by jeffeastman** [comment]
Recommendation 11 deals with 2 of the 3 threats in "Triple Threat". The Rx of muscle relaxants (Flexeril in my tests) in addition just makes death even more likely. Probably any 2 of the 3 pose significant mortality risks.

**Comment by JPercival** [comment]
This is actually related to the [opioid-cds](https://github.com/cqframework/opioid-cds-r4) project.
