### ISSUE TITLE
Read data from  filesystem

### ISSUE THREAD

**Issue by jmistry65** [DBCG/cqf-ruler#220]
How to use a file system to consume the data from FHIR structure using cqf-ruler instead of using any type relational database?
Is there any way i can read data from files?
It will be really helpful if any sample or example is there.

**Comment by JPercival** [comment]
The cqf-ruler does not support direct file system access. It sets up an h2 database if an existing database connection is specified.

For development purposes you could use the [Atom CQL plugin](https://atom.io/packages/language-cql) to run CQL directly against a file system.
