### ISSUE TITLE
HAPIFHIR 5

### ISSUE THREAD

**Issue by jigneshmpatel** [DBCG/cqf-ruler#224]
HAPI FHIR 5 has added UrlBaseTenantIdentificationStrategy  to support multi-tenancy, as well as partitioning?

Is there any dates to upgrade cqf-ruler to HAPI FHIR 5?

**Comment by JPercival** [comment]
Yes, some upstream projects are being updated to HAPI 5 already and this should be rolled out to the cqf-ruler in the next week or so.

**Comment by JPercival** [comment]
Hi. This work is done on the https://github.com/DBCG/cqf-ruler/tree/feature-hapi-502 branch. We've been waiting to merge until the HL7 connectathon is complete.
