### ISSUE TITLE
Fentanyl Patch MME=504 Too High

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#23]
From https://www.cms.gov/Medicare/Prescription-Drug-Coverage/PrescriptionDrugCovContra/Downloads/Opioid-Morphine-EQ-Conversion-Factors-March-2015.pdf:

`The MME conversion factor for fentanyl patches is based on the assumption that one milligram of parenteral fentanyl is equivalent to 100 milligrams of oral morphine and that one patch delivers the dispensed micrograms per hour over a 24 hour day. Example: 25 ug/hr fentanyl patch * 24 hrs = 600 ug/day fentanyl = 60 mg/day oral morphine milligram equivalent. In other words, the conversion factor not accounting for days of use would be 60/25 or 2.4. However, since the fentanyl patch remains in place for 3 days, we have multiplied the conversion factor by 3 (2.4 X 3 = 7.2). In this example, MME/day for ten 25 μg/hr fentanyl patches dispensed for use over 30 days would work out as follows: Example: 25 ug/hr fentanyl patch * (10 patches/30 days)* 7.2 = 60 MME/day.`

A 75 mcg/day patch ought to be 180mme. Still way too high but not 504

**Comment by jeffeastman** [comment]
When I substitute the 25 mcg/day patch in the hook request, it returns MME=144. This is not 1/3 of the 75 mcg/day calculated Mme and is 2.4 times higher than the CDC value above. Looks like the calculation is not taking the 2.4 multiplier into account, since 144 = 2.4 * 60.

**Comment by c-schuler** [comment]
Please provide the request JSON

**Comment by jeffeastman** [comment]
```
{
  "hook": "medication-prescribe",
  "hookInstance": "5bacb720-f493-4fe7-8750-c02595cbb72b",
  "fhirServer": "http://localhost:8080/cqf-ruler/baseDstu3",
  "user": "Practitioner-2516",
  "patient": "Patient-1121",
  "context": [
{
  "resourceType": "MedicationRequest",
  "status": "active",
  "medicationCodeableConcept": {
    "coding": [
      {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "197696",
        "display": "Fentanyl 75 MCG/HR 3 Day Transdermal Patch"
      }
    ]
  },
  "subject": {
    "reference": "Patient/Patient-1121",
    "display": "Jerry Phillip Goodwall [80]"
  },
  "authoredOn": "2017-01-01T00:00:00-05:00",
  "reasonCode": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "82423001",
          "display": "Chronic pain"
        }
      ],
      "text": "Chronic pain"
    }
  ],
  "dosageInstruction": [
    {
      "text": "Apply once every three days for pain.",
      "timing": {
        "repeat": {
          "count": 1,
          "durationUnit": "d",
          "frequency": 1,
          "period": 3
        }
      },
      "asNeededBoolean": false,
      "doseQuantity": {
        "value": 1,
        "unit": "tbl",
        "system": "http://unitsofmeasure.org",
        "code": "tbl"
      }
    }
  ],
  "dispenseRequest": {
    "quantity": {
      "value": 30,
      "unit": "day",
      "system": "http://unitsofmeasure.org",
      "code": "d"
    }
  }
}]
}
```

**Comment by c-schuler** [comment]
There were a couple factors contributing to this issue:
1. When I converted the Access db to SQLite, the decimal precision defaulted to 2 places. So 0.075 changed to 0.07 during the conversion.
2. The GetDailyDosage function in the OMTK library wasn’t taking doses per day into account.

These two factors led to the following (incorrect) calculation:
70*1*7.2 = 504mg/day

I have updated the db and the OMTK library (sent to you via email) and am now getting the following calculation:
75*0.33333333*7.2 = 179.9999982mg/day

Let me know if you are getting the same results with the updates I sent.

**Comment by jeffeastman** [comment]
I'm not getting that result with those updates in the latest cqf-ruler. I verified the .db and the OMTK libraries are the ones you sent:

Sending 'POST' request to URL: http://localhost:8081/cqf-ruler/cds-services/cdc-opioid-guidance
{
  "hook": "medication-prescribe",
  "hookInstance": "5bacb720-f493-4fe7-8750-c02595cbb72b",
  "fhirServer": "http://localhost:8081/cqf-ruler/baseDstu3/",
  "user": "Practitioner-2516",
  "patient": "Patient-1121",
  "context": [
{
  "resourceType": "MedicationRequest",
  "status": "active",
  "medicationCodeableConcept": {
    "coding": [
      {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "197696",
        "display": "Fentanyl 75 MCG/HR 3 Day Transdermal Patch"
      }
    ]
  },
  "subject": {
    "reference": "Patient/Patient-1121",
    "display": "Jerry Phillip Goodwall [80]"
  },
  "authoredOn": "2017-01-01T00:00:00-05:00",
  "reasonCode": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "82423001",
          "display": "Chronic pain"
        }
      ],
      "text": "Chronic pain"
    }
  ],
  "dosageInstruction": [
    {
      "text": "Apply once every three days for pain.",
      "timing": {
        "repeat": {
          "count": 1,
          "durationUnit": "d",
          "frequency": 1,
          "period": 3
        }
      },
      "asNeededBoolean": false,
      "doseQuantity": {
        "value": 1,
        "unit": "tbl",
        "system": "http://unitsofmeasure.org",
        "code": "tbl"
      }
    }
  ],
  "dispenseRequest": {
    "quantity": {
      "value": 30,
      "unit": "day",
      "system": "http://unitsofmeasure.org",
      "code": "d"
    }
  }
}]
}

Response = 200
{
  "cards": [
    {
      "links": [
        {
          "label": "CDC guideline for prescribing opioids for chronic pain",
          "url": "https://guidelines.gov/summaries/summary/50153/cdc-guideline-for-prescribing-opioids-for-chronic-pain---united-states-2016#420"
        },
        {
          "label": "MME Conversion Tables",
          "url": "https://www.cdc.gov/drugoverdose/pdf/calculating_total_daily_dose-a.pdf"
        }
      ]
    },
    {
      "summary": "High risk for opioid overdose - taper now",
      "indicator": "warning",
      "detail": "Total morphine milligram equivalent (MME) is 540.00000mg/d. Taper to less than 50."
    }
  ]
}

**Comment by c-schuler** [comment]
It appears like the OMTK library I sent you wasn't updated with the new logic. Sorry about that! Please load the OMTKLogic library from this [bundle](https://github.com/DBCG/cqf-ruler/blob/master/src/test/resources/org/opencds/cqf/cdc-opioid-guidance-bundle.json) and try again.

**Comment by jeffeastman** [comment]
I'm still getting the same result with this. Can you take a look at the hook request? Might be the dosageInstruction??

```
testJerryFentaNYLNoPrefetch:
2018-01-22 12:58:45 INFO  FhirContext:162 - Creating new FHIR context for FHIR version [DSTU3]

Sending 'POST' request to URL: http://localhost:8080/cqf-ruler/cds-services/cdc-opioid-guidance
{
  "hook": "medication-prescribe",
  "hookInstance": "5bacb720-f493-4fe7-8750-c02595cbb72b",
  "fhirServer": "http://localhost:8080/cqf-ruler/baseDstu3/",
  "user": "Practitioner-2516",
  "patient": "Patient-1121",
  "context": [
{
  "resourceType": "MedicationRequest",
  "status": "active",
  "medicationCodeableConcept": {
    "coding": [
      {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "197696",
        "display": "Fentanyl 75 MCG/HR 3 Day Transdermal Patch"
      }
    ]
  },
  "subject": {
    "reference": "Patient/Patient-1121",
    "display": "Jerry Phillip Goodwall [80]"
  },
  "authoredOn": "2017-01-01T00:00:00-05:00",
  "reasonCode": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "82423001",
          "display": "Chronic pain"
        }
      ],
      "text": "Chronic pain"
    }
  ],
  "dosageInstruction": [
    {
      "text": "Apply once every three days for pain.",
      "timing": {
        "repeat": {
          "count": 1,
          "durationUnit": "d",
          "frequency": 1,
          "period": 3
        }
      },
      "asNeededBoolean": false,
      "doseQuantity": {
        "value": 1,
        "unit": "tbl",
        "system": "http://unitsofmeasure.org",
        "code": "tbl"
      }
    }
  ],
  "dispenseRequest": {
    "quantity": {
      "value": 30,
      "unit": "day",
      "system": "http://unitsofmeasure.org",
      "code": "d"
    }
  }
}]
}

Response = 200
{
  "cards": [
    {
      "links": [
        {
          "label": "CDC guideline for prescribing opioids for chronic pain",
          "url": "https://guidelines.gov/summaries/summary/50153/cdc-guideline-for-prescribing-opioids-for-chronic-pain---united-states-2016#420"
        },
        {
          "label": "MME Conversion Tables",
          "url": "https://www.cdc.gov/drugoverdose/pdf/calculating_total_daily_dose-a.pdf"
        }
      ]
    },
    {
      "summary": "High risk for opioid overdose - taper now",
      "indicator": "warning",
      "detail": "Total morphine milligram equivalent (MME) is 540.00000mg/d. Taper to less than 50."
    }
  ]
}
```

**Comment by c-schuler** [comment]
The periodUnit needs to be specified:
```
"repeat": {
  "count": 1,
  "durationUnit": "d",
  "frequency": 1,
  "period": 3,
  "periodUnit": "d" 
}
```
That is necessary to get the correct daily frequency.

**Comment by jeffeastman** [comment]
Yup, that fixed it. Updating my tests and closing this issue.
