### ISSUE TITLE
$evaluate-measure operation errors when using MATGlobalCommonFunctions_FHIR*

### ISSUE THREAD

**Issue by JeffreyTaylor** [DBCG/cqf-ruler#231]
In recent versions of the cqf-ruler, `$evaluate-measure` is returning errors when using the `MATGlobalCommonFunctions_FHIR`.

You can see the error for yourself here: http://cqm-sandbox.alphora.com/cqf-ruler-r4/fhir/Measure/measure-EXM130-FHIR4-7.2.000/$evaluate-measure?reportType=patient-list&periodStart=2019-01-01&periodEnd=2019-12-31.

This is also happening to me when I run the current develop branch for both STU3 and R4.

I'm able to get around this problem right now by using an older version of this project (specifically, using this docker container: docker run -p 8080:8080 contentgroup/cqf-ruler)

The error is here:
```
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Failed to call access method: java.lang.IllegalArgumentException: [unknown[69:82, 69:82]Syntax error at from, MATGlobalCommonFunctions_FHIR4-4.0.000[69:74, 69:92]Could not resolve identifier timezone in the current library., MATGlobalCommonFunctions_FHIR4-4.0.000[292:19, 292:53]Could not resolve membership operator for terminology target of the retrieve., unknown[69:82, 69:82]Syntax error at from, MATGlobalCommonFunctions_FHIR4-4.0.000[69:74, 69:92]Could not resolve identifier timezone in the current library., MATGlobalCommonFunctions_FHIR4-4.0.000[292:19, 292:53]Could not resolve membership operator for terminology target of the retrieve.]</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Failed to call access method: java.lang.IllegalArgumentException: [unknown[69:82, 69:82]Syntax error at from, MATGlobalCommonFunctions_FHIR4-4.0.000[69:74, 69:92]Could not resolve identifier timezone in the current library., MATGlobalCommonFunctions_FHIR4-4.0.000[292:19, 292:53]Could not resolve membership operator for terminology target of the retrieve., unknown[69:82, 69:82]Syntax error at from, MATGlobalCommonFunctions_FHIR4-4.0.000[69:74, 69:92]Could not resolve identifier timezone in the current library., MATGlobalCommonFunctions_FHIR4-4.0.000[292:19, 292:53]Could not resolve membership operator for terminology target of the retrieve.]"
    }
  ]
}
```

**Comment by JPercival** [comment]
The cqf-ruler updated to the CQL translator 1.4 which currently doesn't support CQL 1.3. The timezone keyword was removed.

In the medium term the CQL translator will be updated to be able to target multiple versions of CQL. This will allow backwards compatibility. That work is being tracked with cqframework/clinical_quality_language#551

In the short term, you may be able to use the updated version of [MATGlobalCommonFunctions](https://github.com/DBCG/connectathon/blob/master/fhir401/input/pagecontent/cql/MATGlobalCommonFunctions-5.0.000.cql)

**Comment by JeffreyTaylor** [comment]
This information is helpful. Thank you @JPercival!

**Comment by JPercival** [comment]
The cqf-ruler now support multiple language levels for CQL.
