### ISSUE TITLE
Resolving lib names by ids in measure bundle.

### ISSUE THREAD

**Issue by cday-semanticbits** [DBCG/cqf-ruler#269]
I was trying to run a measure bundle exported from MAT in CQFRuler and noticed that it needed the ID of the measure library to match the cql library name (from the lib URL i think in the measure). To fix this on the MAT side we changed the measure id and all lib ids to be the cql library name. With that fix it works in CQFRuler. I mentioned this to Bryn and he wanted me to create an issue for this to take a look at it not libs by library.id.

**Comment by JPercival** [comment]
Libraries are now resolved by name (dstu3) or URL (r4+)
