### ISSUE TITLE
$submit-data operation parameter should be camelCase

### ISSUE THREAD

**Issue by mgramigna** [DBCG/cqf-ruler#283]
According to [the spec](https://www.hl7.org/fhir/measure-operation-submit-data.html) for the operation, the `measureReport` parameter should be camelCase.

In the operation definition below, the parameter is named `measurereport`. This causes a null pointer exception when the operation is called with a camelCase `measureReport` parameter:

https://github.com/DBCG/cqf-ruler/blob/29e5a37fad5ec1890d74c0b087920049e76ef30d/r4/src/main/java/org/opencds/cqf/r4/providers/MeasureOperationsProvider.java#L590

**Comment by JPercival** [comment]
Resolved by #284
