### ISSUE TITLE
Much of Tester UI Functionality is Broken on Tomcat at Least

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#29]
Try doing a Search on a resource where there are > 10 of them, then press >| Next Page. Nothing happens. Also, try the CRUD Operations. They all fail to do anything.

**Comment by c-schuler** [comment]
Just checked this in my local instance and http://measure.eval.kanvix.com/cqf-ruler/tester/... Everything seems to be working just fine.

**Comment by jeffeastman** [comment]
I bet you’re running it in Jetty? Tomcat is broken. Maybe some of the same issue as with the e500s on the hook requests?

**Comment by c-schuler** [comment]
Yes, I am using Jetty. So this is a Tomcat issue then... Apologies for my slow progress on that front. I will be working on that today. Stay tuned.

**Comment by jeffeastman** [comment]
I just noticed I’m on a pretty old Tomcat version. I will update and let you know.

Jeff

**Comment by jeffeastman** [comment]
This is an old Tomcat issue. I upgraded to 8.5 and all is good now.

**Comment by jeffeastman** [comment]
Very weird. When I upgraded my laptop's tomcat, the problem went away. On the AWS server, however, it remains even after tomcat upgrade. Reopening while I investigate further.

**Comment by jeffeastman** [comment]
Its somewhere in my branding fixes. Closing this again.
