### ISSUE TITLE
Question About Libraries

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#3]
The database-init-bundle.json contains two flavors of Library:  text/cql and application/elm+xml. The Measure Processor examples refer to the elm libraries.

- What is the function of the CQL libraries?
- Are they automatically converted into ELM inside the cqf-ruler?
- If so, where?
- Where in the cqf-ruler are the ELM libraries evaluated?

Pointers into the code would be useful in helping me understand it.

**Comment by jeffeastman** [comment]
Just found the DBCG/cql_engine so making some progress...

**Comment by c-schuler** [comment]
Hi Jeff,

The function of CQL libraries is to provide the basic unit of code organization for CQL. Each CQL file contains a single library, which may reference any number of other libraries. Libraries may also be declared with a specific version. 
For example:
`library example version '1.0'`

The main use of CQL libraries within the cqf-ruler is to provide the executable logic for the various operations available. For example, during measure processing, a Measure resource contains a [library reference](https://github.com/DBCG/cqf-ruler/blob/master/src/main/resources/col/measures/col.xml#L26-L28) that is used to determine population groupings. For example, the following [population criteria](https://github.com/DBCG/cqf-ruler/blob/master/src/main/resources/col/measures/col.xml#L46-L52) refers to the following [named expression](https://github.com/DBCG/cqf-ruler/blob/master/src/main/resources/col/libraries/col.elm.xml#L86-L108) within the col-logic library. When the measure is executed, the expressions specified in the population criteria are executed ([see here](https://github.com/DBCG/cql_engine/blob/master/cql-engine-fhir/src/main/java/org/opencds/cqf/cql/data/fhir/FhirMeasureEvaluator.java#L40)) to determine whether or not to include a patient within the population for the MeasureReport.

[Here](https://github.com/DBCG/cqf-ruler/blob/master/src/main/java/org/opencds/cqf/config/STU3LibrarySourceProvider.java) is where Library translation from CQL to ELM within the cqf-ruler occurs. There is also a mechanism to expose referenced libraries to the cql-engine [here](https://github.com/DBCG/cqf-ruler/blob/master/src/main/java/org/opencds/cqf/config/STU3LibraryLoader.java#L65-L96)

ELM libraries (or translated libraries) are evaluated in many places in the cqf-ruler, depending on the operation. Libraries are evaluated using the [Context](https://github.com/DBCG/cql_engine/blob/master/cql-engine/src/main/java/org/opencds/cqf/cql/execution/Context.java) class within the cql-engine.
Here are some examples:
[PlanDefinition $apply operation](https://github.com/DBCG/cqf-ruler/blob/master/src/main/java/org/opencds/cqf/providers/PlanDefinitionResourceProvider.java#L189)
[CqlExecutionProvider](https://github.com/DBCG/cqf-ruler/blob/master/src/main/java/org/opencds/cqf/providers/CqlExecutionProvider.java#L129)

I hope that is helpful! Please let me know if you have any more questions.

**Comment by jeffeastman** [comment]
Yes, thanks, very helpful. I've been reading the code and have discovered most of these independently so you're reinforcing that I'm on the right track. Finding the cql_engine was huge and I can build it from the command line but so far IntelliJ and Eclipse don't like something about its Gradle configuration. Since I don't speak Gradle (or IntelliJ for that matter) its frustrating

IJ says Error: Unable to make the module: cal_engine, related gradle configuration was not found. Re-import the Gradle project and try again. But this is meaningless to me. I did try upgrading Gradle to 4.0.1 to no avail.

Eclipse won't even import the project. It won't import Maven projects either. Maybe some secret sauce I don't have?

I did try adding the cql-engine-1.2.20-SNAPSHOT.jar into PatientGen and tried to run this small test:

```
	@Test
	public void testZikaLibrary() throws IOException, JAXBException {
		Library lib = CqlLibraryReader.read(new File("output/libraries/zika-virus-intervention-logic.cql"));
		Context cxt = new Context(lib);
		assertNotNull(cxt);

```
but this throws `java.lang.NoClassDefFoundError: org/jvnet/jaxb2_commons/lang/Equals` and that's where I am stuck right now.

**Comment by jeffeastman** [comment]
What I'd really like to be able to do is evaluate Measures against the generated resources I have in memory.

**Comment by jeffeastman** [comment]
Interesting. the CQLLibraryReader will read .xml but not cql. After adding a few more jars to my class path, this works.

```
	@Test
	public void testCBPLogic() throws IOException, JAXBException {
		Library lib = CqlLibraryReader.read(new File("output/cbp-logic.elm.xml"));
		Context cxt = new Context(lib);
		assertNotNull(cxt);
	}

```

**Comment by c-schuler** [comment]
I just pushed some documentation for building the cql_engine project and importing it into IntelliJ [here](https://github.com/DBCG/cql_engine/wiki/Building-the-project). Hope that helps.

**Comment by c-schuler** [comment]
BTW, the Gradle configuration error and the NoClassDefFoundError were due to a missing dependency in the engine. Pull in the latest for the fix. Apologies for the confusion...

**Comment by jeffeastman** [comment]
Works for me too. Thanks
