### ISSUE TITLE
e500 in DMS Evaluation

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#32]
For _some patients_, I'm getting an NPE exception in IncludedInEvaluator.included(..) because the precisions of the left and right Intervals are different in `DMS QueryEvaluator 214's` where clause:
```
left = Interval [ 2017-09-01T00:00:00, 2017-09-01T00:00:00 ]
right = Interval [ 2017-09-01T00:00:00.000, 2017-12-30T23:59:59.999 ]
```
This is because _TimeBaseTemporal.compareTo(..)_ returns null in this situation. The query & where clause is:
```
              <source localId="214" xsi:type="Query">
                  <source localId="203" alias="E">
                     <expression localId="202" name="Depression Encounters" xsi:type="ExpressionRef"/>
                  </source>
                  <where localId="208" xsi:type="IncludedIn">
                     <operand localId="206" name="PeriodToIntervalOfDT" xsi:type="FunctionRef">
                        <operand localId="205" path="period" scope="E" xsi:type="Property"/>
                     </operand>
                     <operand localId="207" name="Assessment Period Three" xsi:type="ExpressionRef"/>
                  </where>
```
Haven't yet tracked down why this is occurring, so more to come on this.

**Comment by jeffeastman** [comment]
Looks to me like _compareTo(..)_ isn't handling this right, because Instants **left** & **right** are identical and they're being used for the other comparisons.
```
        Instant left = this.jodaDateTime.toInstant();
        Instant right = other.jodaDateTime.toInstant();

        for (int i = 0; i < size; ++i) {
            if (left.get(DateTime.getField(i)) > right.get(DateTime.getField(i))) {
                return 1;
            }
            else if (left.get(DateTime.getField(i)) < right.get(DateTime.getField(i))) {
                return -1;
            }
        }

        if (differentPrecisions) {
            return null;
        }

```

**Comment by duncand** [comment]
Does this bug that I reported https://github.com/DBCG/cql_engine/issues/39 look related to yours at all?  There seems to be a theme.

**Comment by jeffeastman** [comment]
Perhaps, but digging into the spec, I see (p49): "Note that when determining equality [of dates], these semantics imply that if either date/time has unspecified components, the result of the comparison will be unknown [null]." In the above situation, since the **right** interval is more fully specified than the **left** it seems appropriate that _compareTo(..)_ returns **null**.

Jumping up a level to the calling `IncludedInEvaluator.included(..)`, the spec (p54) says: "Each of these operators [including _IncludedIn_] returns true if the intervals X and Y are in the given relationship to each other. If either or both arguments are null, the result is null. Otherwise, the result is false.". So this leads me to believe that lines 44-45:
```
            return (LessOrEqualEvaluator.lessOrEqual(rightStart, leftStart)
                    && GreaterOrEqualEvaluator.greaterOrEqual(rightEnd, leftEnd));
```
Are not correctly dealing with the fact than `LessOrEqualEvaluator.lessOrEqual(rightStart, leftStart)` can, and in this instance does, return **null**. Throwing an NPE isn't correct behavior. I believe that a correct implementation would be:
```
            Boolean startCompare = LessOrEqualEvaluator.lessOrEqual(rightStart, leftStart);
            Boolean endCompare = GreaterOrEqualEvaluator.greaterOrEqual(rightEnd, leftEnd);
            if (startCompare == null || endCompare == null)
                return null;
            else
                return (startCompare && endCompare);
```
Of course, in this example, still it begs the question of why the CQL `"PeriodToIntervalOfDT"` and `"Assessment Period Three"` are returning incompatible Intervals.

**Comment by jeffeastman** [comment]
Looking into the last question, `"Assessment Period Three"` (also One and Two) are defined as:
`	Interval[start of "Measurement Period" + 8 months, end of "Measurement Period" )
`
which is compiled into:
```
      <def localId="46" name="Assessment Period Three" context="Patient" accessLevel="Public">
         <annotation xsi:type="a:Annotation">
              (snip)
        <expression localId="45" lowClosed="true" highClosed="false" xsi:type="Interval">
            <low localId="42" xsi:type="Add">
               <operand localId="40" xsi:type="Start">
                  <operand localId="39" name="Measurement Period" xsi:type="ParameterRef"/>
               </operand>
               <operand localId="41" value="8" unit="months" xsi:type="Quantity"/>
            </low>
            <high localId="44" xsi:type="End">
               <operand localId="43" name="Measurement Period" xsi:type="ParameterRef"/>
            </high>
         </expression>
      </def>
```
Here it seems completely reasonable that 
`right = Interval [ 2017-09-01T00:00:00.000, 2017-12-30T23:59:59.999 ]`

So what about `"PeriodToIntervalOfDT"`?

The PatientGen code that constructs the Encounter's effective time is
```
		Period period = new Period().setStart(new Date(startDateTime)).setEnd(new Date(endDateTime));
		obj.setPeriod(period);
```
 and the start and end values are both Longs, so there should be adequate millisecond precision when the resource is created. By the time the flow gets to `PropertyEvaluator 205`, however, the start and end times of the Encounter are:
```
start = DateTimeType[2017-09-01T00:00:00-04:00]
end = DateTimeType[2017-09-01T00:00:00-04:00]
```
where the myPrecision field of each is SECOND. The CQL isn't taking this inherent difference into account. Since the CQL's `where PeriodToIntervalOfDT(E.period) during "Assessment Period Three"` seems clear and reasonable enough, I'd look for a fix in 
```
define function PeriodToIntervalOfDT(value FHIR.Period):
	Interval[value."start".value, value."end".value]
```

**Comment by jeffeastman** [comment]
OTOH, this situation only presents in 6% of my test patients where the Encounter dates are exactly equal to one of the assessment dates. Fixing the `IncludedInEvaluator.included(..)` bug wouldn't impact the overall results by much even if the patients didn't properly classify.

**Comment by jeffeastman** [comment]
Should have closed this long ago
