### ISSUE TITLE
CDS Hook creation requires ValueSet and Library reference

### ISSUE THREAD

**Issue by goelalex** [DBCG/cqf-ruler#330]
https://github.com/DBCG/cqf-ruler/wiki/PlanDefinition-$apply-Operation

While the CDS hook is generated from the PlanDefinition, it requires the Library and ValueSet to function correctly as dependencies. it would be helpful if the wiki mentioned that.

**Comment by JPercival** [comment]
Update the wiki page to mention that Libraries and ValueSets are required.
