### ISSUE TITLE
Update CDS Hooks request processing to use PlanDefinition library

### ISSUE THREAD

**Issue by xmlmodeling** [DBCG/cqf-ruler#36]
I am planning for expanded use of cqf-ruler for CDS Hooks processing during the May HL7 FHIR connectathon.  Several issues must be fixed for more general use, this is the first.

I just created a PR to remove use of hard-coded library ID for CDS Hooks request processor, e.g. "patient-view" and instead load libraries specified in PlanDefinition.  If acceptable, the other two request processor must be updated also, similar to PatientViewProcessor.  Also, the examples for BCS, CCS, and COL must be updated to not use the same library name, "patient-view".

**Comment by bvdh** [comment]
Dave,

This is an interesting approach but different from how I understand the specification should work. As is explained in [https://build.fhir.org/clinicalreasoning-cds-on-fhir.html], the hook refers to a trigger and not a library. 
So when the condition of the hook is present - all actions of all plan definitions in the repository that have the corresponding hook as trigger will be run. The plan definition will indicate the Libaries to use.

Bas

**Comment by xmlmodeling** [comment]
Hi Bas,

Unless I missed something in the current cqf-ruler code base, the current
support for CDS Hooks completely ignores all Library references from
PlanDefinition.  Instead, the reference to Library/patient-view is
hard-coded in the PatientViewProcessor.  My PR simply modifies this logic
to load and use a PlanDefinition's referenced libraries.  As currently
implemented, there can be only one Library with id 'patient-view' used for
ALL patient-view hooks in a given server instance.  My PR eliminates that
constraint.

There are more fundamental changes also needed in cqf-ruler to support CDS
Hooks discovery, along the lines that you described.  Current
implementation for hooks discovery is all hard-coded.  We had a
conversation in New Orleans after the Thursday Care Plan review session
about collaborating on care planning and protocol definitions for the
Cologne FHIR connectathon.  I recently got my travel approved to attend, so
will be posting the wiki proposal to organize a Care Planning & Management
track in Cologne, similar to the track we had in New Orleans but with
increased emphasis on PlanDefinition and CDS Hooks.  I would by very happy
to work with you on enhancing cqf-ruler CDS Hooks capabilities to test in
May.

Thanks,
  Dave Carlson
  dcarlson@clinicalcloud.solutions

**Comment by c-schuler** [comment]
Thank you for raising this issue Dave!
You are right that the CDS Hooks implementation needs a lot of work. Luckily, I am in the process of a substantial refactor to address several issues including those brought up here. I will reference this issue in my commits to the [cds-hooks-refactor](https://github.com/DBCG/cqf-ruler/tree/cds-hooks-refactor) branch so you can track my progress. I also could make you a reviewer for the code once I issue a pull request if you'd like.

**Comment by c-schuler** [comment]
@xmlmodeling is this still an issue? If not, please close. Thanks!
