### ISSUE TITLE
FHIRActivityDefinitionResourceProvider is not accessible for $apply operation

### ISSUE THREAD

**Issue by xmlmodeling** [DBCG/cqf-ruler#37]
This is apparently a known issue in FHIRPlanDefinitionResourceProvider, because it's commented out with TODO as shown below.  The temporary fix uses the DataProvider server when attempting to invoke ActivityDefinition $apply operation, but this fails when the CDS Hooks request uses a data server that is different from the cql-ruler server.  At this time, when using ActivityDefinition as part of a plan, the data server must be cql-ruler.  I want to use HSPC Sandbox for my data server, but that is not possible with current build.

 // TODO - fix this
//  FHIRActivityDefinitionResourceProvider activitydefinitionProvider = (FHIRActivityDefinitionResourceProvider) provider.resolveResourceProvider("ActivityDefinition");

**Comment by c-schuler** [comment]
This has been addressed in the latest commit.

**Comment by c-schuler** [comment]
@xmlmodeling is this still an issue? If not, please close. Thanks!
