### ISSUE TITLE
Use knowledge model server for terminology as default

### ISSUE THREAD

**Issue by xmlmodeling** [DBCG/cqf-ruler#38]
In PatientViewProcessor (and all other CDS processors), the terminology server is set to use the data server from the CDS Hooks request, as shown below.  I think that a better default assumption is that the terminology server will be same as the knowledge asset server that hosts the PlanDefinition resources.  In my test environment, I use the HSPC Sandbox for my data server.  I propose that the default setting be changed.

I am not too familiar with HAPI framework and unsure how to modify this code to set the terminology server to be same as the library/model server.  Suggestions?

// TODO - assuming terminology service is same as data provider - not a great assumption...
dstu3Provider.setTerminologyProvider(new FhirTerminologyProvider().withEndpoint(request.getFhirServer()));

**Comment by c-schuler** [comment]
In the latest commit to the cds-hooks-refactor branch, I made the Ruler the terminology provider. I would like a way for users to specify the terminology endpoint (with auth if needed) in the request for cases when they are defining their own hooks, but that is currently beyond CDS Hooks capability.

**Comment by c-schuler** [comment]
@xmlmodeling is this still an issue? If not, please close. Thanks!
