### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by rob-reynolds** [DBCG/cqf-ruler#381]
- Ensure target versions/releases of:
   - [ ] HAPI
   - [ ] CQFTooling
   - [ ] CDSHooks
- [ ] Update master to be a release version (and all the reviews, bug fixes, etc. that that requires)
   - [ ] Regression test each of the operations of all the plugins
- [ ] Passed Travis Build = ready for release
- [ ] Create a Github Release (which creates a tag at the current commit of master)
   - [ ] Choose the "Auto-generate release notes" option
- Travis does the release to Maven, ensure binaries are published to the binaries repository:
   - [ ]  r4: (https://oss.sonatype.org/#view-repositories;public~browsestorage~org/opencds/cqf/cqf-ruler-r4)
   - [ ] stu3: (https://oss.sonatype.org/#view-repositories;public~browsestorage~org/opencds/cqf/cqf-ruler-dstu3)
- Travis does the release of the image to DockerHub
   - [ ] Ensure the image is published to DockerHub (https://hub.docker.com/r/contentgroup/cqf-ruler)
- [ ] Update master to vNext-SNAPSHOT
- [ ] Ensure all issues included in the release are Closed

**Comment by rob-reynolds** [comment]
Blocked pending the plugin and update Issues.

**Comment by JPercival** [comment]
Released 0.5.0 instead
