### ISSUE TITLE
New Test Data, Odd Results

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#39]
I'm running a larger population of simulated patient encounters and am using the latest cqf-ruler jars. For some measures, I'm seeing larger denominator and numerator results for the whole population (evaluated individually, one patient at a time) than the IPP values. I thought cqf-ruler was manually enforcing IPP membership for the other populations but these results suggest otherwise.

I will debug further to better characterize the issue but am posting this to see if I may have overlooked something.

```
---------------------
Measure = Measure/measure-asf

===== In-memory Summary =====
	denominator 1 = 469
	denominator 2 = 0
	initial-population = 469
	numerator 1 = 0
	numerator 2 = 0


---------------------
Measure = Measure/measure-bcs

===== In-memory Summary =====
	denominator = 64
	initial-population = 64
	numerator = 64


---------------------
Measure = Measure/measure-ccs

===== In-memory Summary =====
	denominator = 792
	initial-population = 180
	numerator = 314


---------------------
Measure = Measure/measure-col

===== In-memory Summary =====
	denominator = 792
	initial-population = 129
	numerator = 292


---------------------
Measure = Measure/measure-dsf

===== In-memory Summary =====
	denominator 1 = 505
	denominator 2 = 6
	initial-population = 505
	numerator 1 = 505
	numerator 2 = 6


---------------------
Measure = Measure/measure-dms

===== In-memory Summary =====
	denominator 1 = 792
	denominator 2 = 792
	denominator 3 = 792
	initial-population = 5
	numerator 1 = 6
	numerator 2 = 6
	numerator 3 = 6


---------------------
Measure = Measure/measure-drr

===== In-memory Summary =====
	denominator 1 = 2
	denominator 2 = 2
	denominator 3 = 2
	initial-population = 5
	numerator 1 = 2
	numerator 2 = 1
	numerator 3 = 1


---------------------
Measure = Measure/measure-pvs

===== In-memory Summary =====
	denominator = 91
	initial-population = 91
	numerator = 26

```

**Comment by c-schuler** [comment]
Hmm. That's odd. I haven't made any recent changes to the measure evaluation logic. I'll run some tests and see if I can reproduce this. Thanks Jeff!

**Comment by jeffeastman** [comment]
I’m going to try to better characterize this one today. It only seems to apply to some measures.

**Comment by jeffeastman** [comment]
Looking at only ccs, try evaluating it against any male patient in the age range. These patients aren't in the IPP because they're not female, but the denominator logic is just **true** so apparently the IPP membership isn't being enforced.
```
Clarence McFarland Herrera MD [44]  (Practitioner-2113) is in denominator
Wallace Johnnie Garza MD [43]  (Practitioner-2114) is in denominator
Ronnie Knapp Hardin MD [44]  (Practitioner-2115) is in denominator
Clive Hector Greenbody [35]  (Practitioner-2241) is in denominator
Jerry Phillip Goodwall [81]  (Patient-1121) is in denominator
Terry Bradford Green MD [41]  (Practitioner-1108) is in denominator
```

I'm also seeing similar issues with col, where very young patients that aren't IPP are in the denominator because it evaluates to **true**.

**Comment by jeffeastman** [comment]
Running this in memory, and looking at the code, I don't see how the above could occur. In this snippet from _FhirMeasureEvaluator.evaluate(...)_ it shows that only members of the **initialPopulation** are screened for the other PopulationComponents.

It does seem redundant to evaluate the code for initial-population twice though, given that the count should always be equal to _initialPopulation.size()_. A shortcut here seems appropriate.

I'm still trying to figure out why the numerator and denominator calculations in my in-memory test are always the same as the IPP. Will post more once I get it all working.

```
        List<Patient> initialPopulation = initalPopulation(measure, population, context);

        // for each measure group
        for (Measure.MeasureGroupComponent group : measure.getGroup()) {
            MeasureReport.MeasureReportGroupComponent reportGroup = new MeasureReport.MeasureReportGroupComponent();
            reportGroup.setIdentifier(group.getIdentifier());
            report.getGroup().add(reportGroup);

            for (Measure.MeasureGroupPopulationComponent pop : group.getPopulation()) {
                int count = 0;
                // Worried about performance here with big populations...
                for (Patient patient : initialPopulation) {
                    context.setContextValue("Patient", patient.getIdElement().getIdPart());
                    Object result = context.resolveExpressionRef(pop.getCriteria()).evaluate(context);
                    if (result instanceof Boolean) {
                        count += (Boolean) result ? 1 : 0;
                    }

```

**Comment by jeffeastman** [comment]
I think I've discovered the reason: The above _evaluate(...)_ method is only called for population wide statistics. For individual patient statistics, another _evaluate(...)_ measure is called and it calls _resolveGroupings(...)_ which does not have the same IPP logic check for the other population components.

So, IPP might return false, but since numerator and denominator do not contain explicit IPP checks the anomalous overall statistics obtain.

I'll see if I can suggest a patch next...

**Comment by jeffeastman** [comment]
Here's a patch that works in memory. I will repopulate my server to be completely positive, but this looks like a solution. Note that I also do not recalculate IPP once it is known to be true.

```
	private MeasureReport resolveGroupings(MeasureReport report, Measure measure, Context context) {
		HashMap<String, Resource> resources = new HashMap<>();

		// for each measure group
		for (Measure.MeasureGroupComponent group : measure.getGroup()) {
			MeasureReport.MeasureReportGroupComponent reportGroup = new MeasureReport.MeasureReportGroupComponent();
			// TODO: Do I need to do this copy? Will HAPI FHIR do this automatically?
			reportGroup.setIdentifier(group.getIdentifier().copy());
			report.getGroup().add(reportGroup);
			Boolean inIPP = null;
			// mirror the same IPP logic as in initialPopulation below
			for (Measure.MeasureGroupPopulationComponent population : group.getPopulation()) {
				if (population.getCode().getCodingFirstRep().getCode().equals("initial-population")) {
					Object result = context.resolveExpressionRef(population.getCriteria()).evaluate(context);
					inIPP = (Boolean) result;
				}
			}
			if (inIPP == null || inIPP)
				for (Measure.MeasureGroupPopulationComponent population : group.getPopulation()) {
					int count = 0;
					if (population.getCode().getCodingFirstRep().getCode().equals("initial-population"))
						// if we got here we already know the count = 1 so why recompute it?
						count = 1;
					else {
						// evaluate the criteria expression, should return true/false, translate to 0/1 for report
						Object result = context.resolveExpressionRef(population.getCriteria()).evaluate(context);
						if (result instanceof Boolean) {
							count = (Boolean) result ? 1 : 0;
						} else if (result instanceof Iterable) {
							for (Object item : (Iterable<?>) result) {
								count++;
								if (item instanceof Resource) {
									resources.put(((Resource) item).getId(), (Resource) item);
								}
							}
						}
					}
					MeasureReport.MeasureReportGroupPopulationComponent populationReport = new MeasureReport.MeasureReportGroupPopulationComponent();
					populationReport.setCount(count);
					populationReport.setCode(population.getCode());
					populationReport.setIdentifier(population.getIdentifier());

					reportGroup.getPopulation().add(populationReport);
				}
		}

```

**Comment by jeffeastman** [comment]
Unfortunately, mvn won't build it for me any more. I'm going to update it and see if that will help.
```
Jeffs-Slate-MacBook-Pro:cqf-ruler jeff$ mvn clean install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.opencds.cqf:cqf-ruler:war:0.1.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 389, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] Inspecting build with total of 1 modules...

```

**Comment by jeffeastman** [comment]
my m2/repository somehow got corrupted. Can build again (whew)

**Comment by jeffeastman** [comment]
In my implementation, the compiler seems to have a problem with this and it jumps to line 41:

```
			// mirror the same IPP logic as in initialPopulation below
			for (Measure.MeasureGroupPopulationComponent population : group.getPopulation()) {
				if (population.getCode().getCodingFirstRep().getCode().equals("initial-population")) {
					Object result = context.resolveExpressionRef(population.getCriteria()).evaluate(context);
					inIPP = (Boolean) result;
				}
			}

```
When I changed the first **population** to **pop**, that seemed to fix it. It may be just in my build because its broken again

**Comment by jeffeastman** [comment]
With the above patch modified as shown, I'm now getting reasonable results when I evaluate each patient in the population for each measure. Don't yet know why Erica is throwing the e500 but its down in the bowels of expression evaluation:

```
===== Server Summary =====
	denominator = 19
	initial-population = 19
	numerator = 7
Getting all server patients...

===== Server Summary =====
	denominator = 26
	initial-population = 26
	numerator = 17
Getting all server patients...
e500 Erika Amy Moore http://localhost:8080/cqf-ruler/baseDstu3/Patient/Patient-6486/_history/1

===== Server Summary =====
	denominator = 33
	initial-population = 33
	numerator = 12

```

**Comment by jeffeastman** [comment]
Erika's throwing a `new IllegalArgumentException(String.format("Cannot In arguments of type '%s' and '%s'.", left.getClass().getName(), right.getClass().getName()))` in `InEvaluator.in(...)` when **left** is a DateTime (2016-01-01T00:00:00) and **right** is an Interval [ 2016-01-01T00:00:00.000, 2017-12-31T00:00:00.000 ]. Seems like we've seen this before but a lot more often in the past. When I try to drop the stack and re-execute the method it no longer throws the exception and returns _null_. 

Go figure...

**Comment by jeffeastman** [comment]
Turns out, this patch is what breaks the build. So there must be some unit tests that no longer work because the code works just fine otherwise.

**Comment by jeffeastman** [comment]
When I comment out _@Test_ for _MeasureProcessingTest_ and _TestMeasureEvaluator_ I can build again, but I have no way to go deeper into why these tests are failing with the patch.

**Comment by c-schuler** [comment]
Apologies for the delay @jeffeastman. I will be addressing this issue today. I will add some some test cases to the suite for ASF, DMS, DRR, DSF, and PVS as well. Could you send me the latest test deck?

**Comment by c-schuler** [comment]
See https://github.com/DBCG/cqf-ruler/wiki/Quality-Measure-Processing for the changes I made to the request format for measure evaluation.

**Comment by c-schuler** [comment]
@jeffeastman: have the latest commits resolved these issues? FYI, as I have been testing these measures, I have been making updates to the CQL in the hedis-ig repo.

**Comment by jeffeastman** [comment]
I’m traveling this week but will test next week and let you know.

**Comment by jeffeastman** [comment]
Closing this issue because results are now much more reasonable
