### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SeanWheelwright** [DBCG/cqf-ruler#431]

**Comment by SeanWheelwright** [comment]
Things we need to document. This should be documentation that we can hand to users. Put it on the website.
- How to tune evaluate measure parameters
- Usage operation documentation
- Walk through of invoking operation locally and get a response
- Evaluate measure
- Platform setup

Reference HAPI. They have good documentation.
- Care Gaps

**Comment by JPercival** [comment]
We could potentially descope this to just updating the wiki pages.

**Comment by c-schuler** [comment]
We also need to capture the changes to how we handle cds hooks requests with prefetch resources. Previous versions attempted to resolve a partially completed prefetch whereas now it assumed to be complete if present.

**Comment by JPercival** [comment]
Scope of work covered, new documentation requirements will be added as new issues.
