### ISSUE TITLE
Address the test ignores

### ISSUE THREAD

**Issue by JPercival** [DBCG/cqf-ruler#453]
There are a few tests that are marked as "Ignored" due to various issues. We need to work through those and address whatever the underlying issue is. could be a badly written test or broken cqf-ruler functionality. Need to work through all the failing tests, figure out root cause for the failures, and add issues as required.

**Comment by chalmarm** [comment]
@JPercival  Following are the places in cqf-ruler that gave me on grep for @Ignore, am I looking at the right spot, seemed those are purposefully commented. Can you please point me to the right folder or place. Thanks,
ExampleServerR5IT.java
ElasticsearchLastNR4IT.java
