### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#46]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.713 s
[INFO] Finished at: 2018-05-15T10:20:14-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project cqf-ruler: Compilation failure
[ERROR] /Users/jeff/gitrepo/cqf-ruler/src/main/java/org/opencds/cqf/providers/FHIRMeasureResourceProvider.java:[88,42] cannot find symbol
[ERROR]   symbol:   method getDao(java.lang.Class<org.hl7.fhir.dstu3.model.Library>)
[ERROR]   location: interface ca.uhn.fhir.jpa.dao.IFhirResourceDao<capture#1 of ? extends org.hl7.fhir.instance.model.api.IAnyResource>
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by c-schuler** [comment]
Thanks Jeff. Looks like this was a change published today on the [HAPI 3.4.0-SNAPSHOT](https://github.com/jamesagnew/hapi-fhir/commit/6f76852e939ccbad93792a11a5c5066b5e09433e#diff-601c0796a9fbc84dc0d08c682d1f36bd). Should be fixed now.

**Comment by jeffeastman** [comment]
Yup. Compiles again, thanks!
