### ISSUE TITLE
Clean-up testing items for consistency and clarity

### ISSUE THREAD

**Issue by rob-reynolds** [DBCG/cqf-ruler#462]
Test settings are set in the test class's properties.

Ensure any necessary settings are in the properties and remove the .yaml file.

**Comment by rob-reynolds** [comment]
Repro
- remove configuration for all but the testing config file
- set a breakpoint on the setter method for a configuration setting
- run test in debug mode

IS: the setter will not be called
Expected: the setter should be called

**Comment by rob-reynolds** [comment]
NOTE: the cr plugin test configuration file has been renamed to application.yaml in a branch.  Do not rename the application.yaml file in this story to prevent a merge conflict.

**Comment by rob-reynolds** [comment]
NOTE: the annotations are also not consistent across the project.
It appears only one is required:
@ConfigurationProperties(prefix = "<value>")

But some have others.

**Comment by rob-reynolds** [comment]
NOTE: additionally, the private instance variables that are collections of configuration are sometimes instantiated.  This is not necessary as the configuration process instantiates them.

Example IS;
private SomeConfigurationCollection config_name = new SomeConfigurationCollection ();

Example SHOULD BE:
private SomeConfigurationCollection config_name;

**Comment by rob-reynolds** [comment]
Note: the RA plugin (and possibly others) specify a configuration collection object for an endpoint configuration that is not necessary.

IS: 
private Report report = new Report();
<plus additional related configuration>

SHOULD BE:
<deleted>

**Comment by rob-reynolds** [comment]
Other plugins might follow the above pattern as well.

All the existing plugins should be checked and updated as applicable.

**Comment by chalmarm** [comment]
> Note: the RA plugin (and possibly others) specify a configuration collection object for an endpoint configuration that is not necessary.
> 
> IS: private Report report = new Report(); [plus additional related configuration]
> 
> SHOULD BE: [deleted]

@rob-reynolds Deleting the entire inner class of Report would cause the failure, @ConfigurationProperties helps load the prefixed properties. Not sure if deleting of Report is required since we only want enabled property and not report property from the yaml. Please advise.
