### ISSUE TITLE
duplicate prefetch template entries for patient in the new cqfruler instance

### ISSUE THREAD

**Issue by 3abdel3ali** [DBCG/cqf-ruler#487]
Hi, when we deploy our libraries and planedefinition resources on the cqfruler, we noticed that the cqfruler duplicates prefetch template entries for patient, as below

*{
"services": [
{
"hook": "order-select",
"name": "PlanDefinition_epidiolexe1rxviewV4",
"title": "PlanDefinition - epidiolexe1rxviewV4",
"id": "epidiolexe1rxviewV4",
"prefetch": {
"item1": "Patient?_id\u003d{{context.patientId}}",
"item2": "Patient?_id\u003dPatient/{{context.patientId}}"
}
},
{
"hook": "order-select",
"name": "PlanDefinition_epidiolexe1rxviewV5",
"title": "PlanDefinition - epidiolexe1rxviewV5",
"id": "epidiolexe1rxviewV5",
"prefetch": {
"item1": "Patient?_id\u003d{{context.patientId}}",
"item2": "Patient?_id\u003dPatient/{{context.patientId}}"
}
}
]
}*

this causes execution errors for cql engine, especially when we use it with the cds-hooks sandbox as the sandbox send 2 patients resources instead of one and the reply is: 

ERROR: Exception in CQL Execution.
Expected a list with at most one element, but found a list with multiple elements.

**Comment by JPercival** [comment]
Appears to be a bug in the FhirQuery generation code, which is in the upsteam cql_engine project. Trying to repro the issue there...

**Comment by c-schuler** [comment]
@JPercival were you able to repro this issue? It seems that the OP is not experiencing the issue any longer.

**Comment by JPercival** [comment]
Resolved before v0.6.0
