### ISSUE TITLE
Evaluate Measure takes longer than Care Gaps

### ISSUE THREAD

**Issue by rob-reynolds** [DBCG/cqf-ruler#492]
Calling $care-gaps is faster than calling $evaluate-measure even though $care-gaps uses evaluateMeasure().

$care-gaps immediately followed by $evaluate-measure:
**Is:**
$care-gaps: 1683ms
![image](https://user-images.githubusercontent.com/13257640/160243401-5100bd34-0e09-4f0c-b1b1-5e06120329d1.png)
$evaluate-measure: 3.74s
![image](https://user-images.githubusercontent.com/13257640/160243682-e5aa1379-d8b1-4b38-af9f-d6f26840518c.png)

**Should be:**
Since $care-gaps is being called first, the expectation is that any caching is warm for the subsequent $evaluate-measure call.  Given this and the fact $care-gaps literally calls evaluateMeasure (https://github.com/DBCG/cqf-ruler/blob/a80853dcc2fda4b601c016bca70622ccbff5d1df/plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/r4/provider/CareGapsProvider.java#L320) the expectation is that the $care-gaps time should always be $evaluate-measure plus additional $care-gaps processing time, i.e., $care-gaps > $evaluate-measure.

Repro:
https://cloud.alphora.com/sandbox/r4/gic/fhir/Measure/$care-gaps?periodStart=2020-01-01&periodEnd=2020-12-31&status=open-gap&status=closed-gap&subject=Patient/numer-EXM130&measureId=ColorectalCancerScreeningsFHIR

https://cloud.alphora.com/sandbox/r4/gic/fhir/Measure/ColorectalCancerScreeningsFHIR/$evaluate-measure?patient=numer-EXM130&periodStart=2020-01-01&periodEnd=2020-12-31

**Comment by rob-reynolds** [comment]
It's kinda a WAG, but I wonder if this could be related to instance vs type invocation.  

Unfortunately, I'm unable to test due to both operations under consideration have instance vs type issues atm, ref https://github.com/DBCG/cqf-ruler/issues/442.

**Comment by JPercival** [comment]
Resolved by #524
