### ISSUE TITLE
mts-support-rckms-2.0.0 Maven dependency fails (building cqf-ruler v0.4.1) - "zip END header not found"

### ISSUE THREAD

**Issue by mattStorer** [DBCG/cqf-ruler#533]
I am trying to build cqf-ruler on tag v0.4.1 using Java 11 / OpenJ9 with Maven 3.5.3 with a fresh local .m2 repository.

running "mvn package" downloads all dependencies (fine) then displays the following:

> [INFO] Compiling 29 source files to C:\git\cqf-ruler-0.4.1\common\target\classes
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] error reading C:\Users\storer\.m2\repository\org\cdsframework\rckms\mts-support-rckms\2.0.0\mts-support-rckms-2.0.0.jar; zip END header not found

followed by loads of errors like these:

> [ERROR] /C:/git/cqf-ruler-0.4.1/common/src/main/java/org/opencds/cqf/common/config/FhirTesterConfig.java:[1,1] cannot access org.opencds.cqf.common.config
>   zip END header not found
> [ERROR] /C:/git/cqf-ruler-0.4.1/common/src/main/java/org/opencds/cqf/common/exceptions/InvalidContextException.java:[1,1] cannot access org.opencds.cqf.common.exceptions
>   zip END header not found
> [ERROR] /C:/git/cqf-ruler-0.4.1/common/src/main/java/org/opencds/cqf/common/helpers/ClientHelper.java:[1,1] cannot access org.opencds.cqf.common.helpers
>   zip END header not found
> [ERROR] /C:/git/cqf-ruler-0.4.1/common/src/main/java/org/opencds/cqf/common/providers/CacheAwareTerminologyProvider.java:[1,1] cannot access org.opencds.cqf.common.providers
>   zip END header not found
> [ERROR] /C:/git/cqf-ruler-0.4.1/common/src/main/java/org/opencds/cqf/common/narrative/JarEnabledCustomThymeleafNarrativeGenerator.java:[1,1] cannot access org.opencds.cqf.common.narrative
>   zip END header not found
> [ERROR] /C:/git/cqf-ruler-0.4.1/common/src/main/java/org/opencds/cqf/common/evaluation/MeasureScoring.java:[1,1] cannot access org.opencds.cqf.common.evaluation
>   zip END header not found
> [ERROR] /C:/git/cqf-ruler-0.4.1/common/src/main/java/org/opencds/cqf/common/retrieve/JpaFhirRetrieveProvider.java:[1,1] cannot access org.opencds.cqf.common.retrieve
>   zip END header not found
> [ERROR] /C:/git/cqf-ruler-0.4.1/common/src/main/java/org/opencds/cqf/common/builders/BaseBuilder.java:[1,1] cannot access org.opencds.cqf.common.builders
>   zip END header not found
> [ERROR] /C:/git/cqf-ruler-0.4.1/common/src/main/java/org/opencds/cqf/common/config/FhirServerConfig.java:[43,8] cannot access java.lang
>   zip END header not found
> [ERROR] /C:/git/cqf-ruler-0.4.1/common/src/main/java/org/opencds/cqf/common/config/FhirServerConfig.java:[40,2] cannot find symbol
>   symbol: class Configuration
> [ERROR] /C:/git/cqf-ruler-0.4.1/common/src/main/java/org/opencds/cqf/common/config/FhirServerConfig.java:[41,2] cannot find symbol
>   symbol: class EnableTransactionManagement
> [ERROR] /C:/git/cqf-ruler-0.4.1/common/src/main/java/org/opencds/cqf/common/config/FhirServerConfig.java:[42,2] cannot find symbol
>   symbol: class ComponentScan
> 
... etc.

I traced down the mts-support-rckms-2.0.0 artifacts in my .m2 repository, and found that indeed, the artifacts are all corrupted (the highlighted artifacts, all 7 KB in size, are corrupted):
![image](https://user-images.githubusercontent.com/979938/174916283-a0ff54f0-e305-4a2d-a039-c1811af2fd87.png)

This is their contents:

> `<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="description" content="Log in to Jira, Confluence, and all other Atlassian Cloud products here. Not an Atlassian user? Sign up for free."/><meta name="google-site-verification" content="HNNnCkeVQ-w56fqPpX2TTEMRmta5QJ-bDunwoaUep-o"/><meta name="apple-itunes-app" content="app-id=1006971684"/><meta name="slack-app-id" content="AC23SDS77"/><link rel="shortcut icon" href="https://aid-frontend.prod.atl-paas.net/atlassian-id/front-end/5.0.338/favicon.ico"/><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/><link rel="preconnect" href="https://t.castle.io"/><link rel="preconnect" href="https://api.segment.io" crossorigin/><link rel="preconnect" href="https://accounts.google.com"/><link rel="preconnect" href="https://sentry.io" crossorigin/><title>Log in with Atlassian account</title><style nonce="wWur8ViVcgVvU3FD6+TJE1rTxDY&#61;">#root{height:100%}.grecaptcha-badge{visibility:hidden}.scriptLoadError{display:flex;align-content:center;background-color:#0747a6;position:absolute;top:0;left:0;width:100%;height:100%;font-size:14px;font-style:normal;font-weight:400;line-height:1.42857142857143;letter-spacing:-.005em;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Fira Sans,Droid Sans,Helvetica Neue,sans-serif}.scriptLoadError .container{color:#fff;margin:0 auto;align-items:center;display:flex;flex-direction:column}.scriptLoadError .content{background:#fff;border-radius:3px;box-shadow:0 10px 10px rgba(0,0,0,.1);box-sizing:border-box;color:#172b4d;padding:48px;width:400px}.scriptLoadError .content{margin-top:48px}.scriptLoadError .content p:first-child{margin-top:0}.scriptLoadError .content a{text-decoration:none;color:#0052cc}.scriptLoadError .logo{margin-top:48px;margin-bottom:0;font-size:40px;line-height:48px}.scriptLoadError .heading{color:#deebff;font-size:24px;font-weight:500;line-height:28px;margin-top:48px}</style><script src="https://metal.prod.atl-paas.net/1.24.0/metal-head.min.js"></script><link href="https://aid-frontend.prod.atl-paas.net/atlassian-id/front-end/5.0.338/static/css/40.fc62f8f3.chunk.css" rel="stylesheet"></head><body data-app-state="{&quot;appConfig&quot;:{&quot;auth0Config&quot;:{&quot;callbackUrl&quot;:&quot;https://id.atlassian.com/login/callback&quot;,&quot;clientId&quot;:&quot;tDP5by46cc3gEck7d2vbHZsqsfrDK6t9&quot;,&quot;domain&quot;:&quot;auth.atlassian.com&quot;,&quot;tenant&quot;:&quot;atlassian-account-prod&quot;,&quot;tokenIssuer&quot;:&quot;https://atlassian-account-prod.pus2.auth0.com&quot;},&quot;bitbucketSignupUrl&quot;:&quot;https://bitbucket.org/account/signup&quot;,&quot;bitbucketSignupUrlOverrideEnabled&quot;:false,&quot;castleAppId&quot;:&quot;337683121243755&quot;,&quot;googleAuthClientId&quot;:&quot;596149463257-9oquqfivs9on8t8erq23c8qso6vk3cp1.apps.googleusercontent.com&quot;,&quot;marketingConsentApiUrl&quot;:&quot;https://preferences.atlassian.com/rest&quot;,&quot;recaptchaEnable&quot;:true,&quot;recaptchaEnterpriseCheckboxKeySite&quot;:&quot;6LfnteAZAAAAAH3vsGy_TA6P6wBH6jtbMqAeVI8k&quot;,&quot;recaptchaEnterpriseInvisibleKeySite&quot;:&quot;6LcTpeAZAAAAACEXJuZmTp5YVTOUVXnN3TYR_fLM&quot;,&quot;segmentIoKey&quot;:&quot;cb2egpwag7&quot;,&quot;sentryUrl&quot;:&quot;https://71e54c28be0d49f0bcd732ab30f35faa@sentry.io/275199&quot;,&quot;contextPath&quot;:&quot;&quot;},&quot;locale&quot;:&quot;en-US&quot;,&quot;csrfToken&quot;:&quot;cdee871e-84d2-4613-915a-24d71faf8b0a&quot;,&quot;hashedCsrfToken&quot;:&quot;b1d758fb098eecd8c2bc5fc486656d4ea053ab40cdaf2fdd39621faf7a888b1d&quot;,&quot;featureFlags&quot;:{&quot;aid_signup.microsoft.auth.enabled&quot;:true,&quot;aid_signup.apple.auth.enabled&quot;:true,&quot;aid_signup.recaptcha_enterprise.enabled&quot;:true,&quot;aid_signup.disallow.bitbucket.username.login&quot;:true,&quot;sign-in-with-slack.enabled&quot;:false,&quot;aid-frontend.google.login.outage.advisory.enabled&quot;:false,&quot;aid-frontend.microsoft.login.outage.advisory.enabled&quot;:false,&quot;aid-frontend.apple.login.outage.advisory.enabled&quot;:false,&quot;aid-frontend.slack.login.outage.advisory.enabled&quot;:false,&quot;aid-frontend.enable-subbranding&quot;:false,&quot;aid-frontend.google.one.tap.enabled&quot;:true,&quot;aid-frontend.growth.login-page-optimisation&quot;:&quot;control-not-enrolled&quot;},&quot;cobranding&quot;:{&quot;application&quot;:&quot;confluence&quot;,&quot;derivedApplication&quot;:&quot;confluence&quot;},&quot;tenantCloudId&quot;:&quot;1dc39d19-5d42-47cc-b076-82eb469cc0b5&quot;,&quot;login&quot;:{}}"><div id="root"><noscript><div class="scriptLoadError"><div class="container"><h1 class="logo">Atlassian</h1><div class="heading">JavaScript is disabled</div><div class="content"><p>You should enable JavaScript to work with this page.</p></div></div></div></noscript><div id="javaScriptLoadError" style="display:none"><div class="scriptLoadError"><div class="container"><h1 class="logo">Atlassian</h1><div class="heading">JavaScript load error</div><div class="content"><p>We tried to load scripts but something went wrong.</p><p>Please make sure that your network settings allow you to download scripts from the following domain:</p><p><b>https://aid-frontend.prod.atl-paas.net/atlassian-id/front-end/5.0.338</b></p></div></div></div></div></div><script nonce="wWur8ViVcgVvU3FD6+TJE1rTxDY&#61;">var mfaServerUrl="",ticket="",requestToken="",postActionURL="",userData={userId:"",email:"",friendlyUserId:"",tenant:"",tenantFriendlyName:""},globalTrackingId="";window.onload=function(){document.getElementById("javaScriptLoadError")&&(document.getElementById("javaScriptLoadError").style.display="block")}</script><script src="https://aid-frontend.prod.atl-paas.net/atlassian-id/front-end/5.0.338/static/js/runtime-main.85590f2f.js"></script><script src="https://aid-frontend.prod.atl-paas.net/atlassian-id/front-end/5.0.338/static/js/40.91a51d32.chunk.js"></script><script src="https://aid-frontend.prod.atl-paas.net/atlassian-id/front-end/5.0.338/static/js/main.502f92dd.chunk.js"></script></body></html>
`

Which looks like this when rendered in a browser:
![image](https://user-images.githubusercontent.com/979938/174917481-9c7d8e0f-3615-4034-abf4-88be015b2e35.png)

This artifact is listed as a dependency for the cqf-tooling project:
https://github.com/cqframework/cqf-tooling/blob/master/pom.xml#L175-L177

Any idea how to resolve this?  I can't find anything in GitHub issues or on the Zulip chat stream about "mts", "rckms", or "zip END header not found".  Documentation [here](https://github.com/DBCG/cqf-ruler/tree/v0.4.1) seems to indicate that "mvn package" is all you need to do to get it to build.

Help, please.

Thanks!

Matt

**Comment by c-schuler** [comment]
Hi Matt. This appears to be an oversight in including a necessary 3rd party repository in the 0.4.1 cqf-ruler pom. I am guessing this wasn't caught because the developers had already acquired the 3rd party jars by building the cqf-tooling project previously. Apologies for that oversight!

The fix is to trash your .m2/repository folder and add the following to the 0.4.1 cqf-ruler pom repositories:
```
<repository>
    <id>support.hln.com-release</id>
    <name>support.hln.com-release</name>
    <url>https://hlnconsulting.jfrog.io/artifactory/libs-release-local/</url>
</repository>
<repository>
    <id>support.hln.com-snapshot</id>
    <name>support.hln.com-snapshot</name>
    <url>https://hlnconsulting.jfrog.io/artifactory/libs-snapshot-local/</url>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
```

**Comment by mattStorer** [comment]
that did the trick!  thanks!
