### ISSUE TITLE
Implement $care-gaps prototype operation for Measure evaluation

### ISSUE THREAD

**Issue by c-schuler** [DBCG/cqf-ruler#55]
In Parameters:
measure ID - String - required
patient ID - String - required
topic - String - required
periodStart - String - required
periodEnd - String - required

Returns a Bundle containing:
Composition resource with human friendly summary of the operation results
MeasureReport resources for results that failed to satisfy the improvementNotation for the Measure

The "topic" parameter identifies which Measures to run and corresponds to the [topic](http://hl7.org/fhir/measure-definitions.html#Measure.topic) property for the Measure resource. Note that this is a prototype and only does patient-level evaluation at this time.

**Comment by jeffeastman** [comment]
I can build this locally and all my tests run
