### ISSUE TITLE
Add validation of parameters for POST requests

### ISSUE THREAD

**Issue by rob-reynolds** [DBCG/cqf-ruler#552]
Validation of parameters for GET requests is currently supported (i.e., query string parameters).  Extend with validation of parameters for other verbs (i.e. body parameters).

Also, update existing usages of the query string parameter validation to use the new body parameters functionality.

**Comment by JPercival** [comment]
Seems unusual that the validation would not work with POST requests. They are parsed from the body of the request prior to the operation implementation being invoked. Can we validation that it doesn't work for POST?

**Comment by rob-reynolds** [comment]
The issue was identified, reported, and addressed by @c-schuler here: https://github.com/DBCG/cqf-ruler/blob/c97f0cfa06f0cff2082f805947dae4fcaf2ddeae/plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/r4/RiskAdjustmentProvider.java#L58.

I don't know what our policy is on validating issues.  I would think the expectation is that the person who identified the issue also validated it, but we know that doesn't always happen.  So when we have issues we suspect aren't valid do we kick them back to the person who identified them or do we have the person who's working on the issue start with validating it's an actual issue?

Maybe the simplest approach is we require a repro.

And in this case we could ask @c-schuler to provide a repro?

**Comment by rob-reynolds** [comment]
I think we should implement templates for issues, across the board: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates.

**Comment by rob-reynolds** [comment]
And make repro a (nearly) required field in bug issues.
