### ISSUE TITLE
Bad error message

### ISSUE THREAD

**Issue by rob-reynolds** [DBCG/cqf-ruler#555]
**Is:**  "diagnostics": "Failed to call access method: java.lang.NullPointerException: Cannot invoke \"org.hl7.fhir.instance.model.api.IBaseResource.getIdElement()\" because \"r\" is null"

**Should be:** an error message that includes a description of the issue

**Repro:**
In the Thunder Client for CQF-Ruler:
1)  run the Knowledge Artifacts - EXM124 - Cervical Cancer Screening request (under DQM, Config)
2) in the Evaluate EXM124 - Numerator request, set the subject to an incorrect value, for example: numer-EXM12
3) run the Evaluate EXM124 - Numerator request

**Comment by c-schuler** [comment]
@mdnazmulkarim is there an update for this issue?

**Comment by mdnazmulkarim** [comment]
This issue has been solved as with SDE design PRs.  
Now we get similar to the the following message:
 "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "HAPI-0971: Resource Patient/hist-closed-HCC18 is not known"
        }
    ]
