### ISSUE TITLE
Implement latest SDE design

### ISSUE THREAD

**Issue by rob-reynolds** [DBCG/cqf-ruler#556]
SDE design has been completed to address the following:
- Supplemental Data Elements and Evaluated Resources are distinct and need to be representing distinctly in the Measure Report
- Supplemental Data Elements in the Measure Report need to reference the Supplemental Data Element specification in the Measure

$measure-evaluation needs to be updated to reflect the updated design:

1. On the MeasureReport, update the the extensions that reference criteria specified on the Measure to be consistent. 

IS: there are a number of different extensions.  

Example:

- population references in evaluatedResource use: "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-populationReference"
- persisted supplemental references use: http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData"

SHOULD BE: consolidate them all to a single extension in the MeasureReport: http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference.

2. For ephemeral (primitive) Supplemental Data Elements, move the reference from evaluatedResource to an extension on the MeasureReport.

IS: persistent (resource) SDEs are referenced by an extension on the MeasureReport and ephemeral SDEs are referenced in the evaluatedResource element.  These references should be consistent.  

SHOULD BE:  move the ephemeral references (to contained Observation resources) to the extension on MeasureReport (use the updated http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference from above).

3. For ephemeral (primitive) Supplemental Data Elements use a guid for the ID.

IS: the Observation that is generated has an encoded id. 

SHOULD BE: the id no longer needs to be encoded.

Example: sde-observation-0A09570A-CCF9-40EA-9D89-C25502F3507C-code-f.  This can now just be the guid 0A09570A-CCF9-40EA-9D89-C25502F3507C.  Note, the id should be unique.  It should NOT match the id of the SDE specified in the Measure.

4. For ephemeral (primitive) Supplemental Data Elements use the supplemental-data code for the code of the Observation that is generated.

IS: an encoding of the criteria expression is used as the code for the Observation that is created.

SHOULD BE: use the supplemental-data code instead.

Example:
```
  "code": {
      "system": "http://terminology.hl7.org/CodeSystem/measure-data-usage",
      "code": "supplemental-data"
  }
```

Also, if the Measure.supplementalData.code has a value, add it as well (but make unique).

Example:
```
"code":{
              "coding": [
                  {
                       "code": {
                          "system": "http://terminology.hl7.org/CodeSystem/measure-data-usage",
                           "code": "supplemental-data"
                         },
                         "code": {
                          "system": "<some special system>",
                           "code": "<some special code>"
                         }
        }
    ]
}
```

5. For ephemeral (primitive) Supplemental Data Elements remove the unnecessary extension on the Observation that is generated.

IS: an encoding of the criteria expression is added as an extension to the Observation that is created.

SHOULD BE: remove it.

Example:
```
{
    "url": "populationId",
    "valueString": "sde-sex"
}
```

6. The Supplemental Data Element extension should include a reference to the SDE specification in the Measure. 

IS: for an ephemeral (primitive) SDE an Observation is created in the contained and that Observation has a code that is either the ID of the SDE specified in the Measure or it's an encoding of the CQL define and there is no information in the reference that's currently in evaluatedResources.

Also, for a persisted (Resource) SDE an extension is added to the MeasureReport and this extension has no information about the SDE specified in the Measure.

The consistent extensions created in item 2. above need to include the information about the SDE specified in the Measure.  

SHOULD BE:  add the ID of the SDE specified in the Measure as a reference extension in to the SDE extension.

Example:
```
{
    "url": "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData",
    "valueReference": {
        "extension": [
            {
                "url": "http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-criteriaReference",
                "valueString": "<ID of SDE specification in the Measure>"
            }
        ],
        "reference": "<SDE resource reference (whether contained or relative [or potentially absolute])>"
    }
}

```

**General Guidance:**
References can be duplicated across evaluatedResources and the SupplementalDataElement extensions (i.e. a given resource can be both an evaluatedResource and a SupplementalDataElement), but they should be unique within each (i.e., a given resource should never have more than one entry in evaluatedResource and a given resource should never have more than one entry in the SupplementalDataElement extension).

If the specification in the Measure does not have an ID, do not error, just skip.  We will include a Warning noted the item was skipped in a future feature.

**Comment by SeanWheelwright** [comment]
PR to be submitted Monday by EOD

**Comment by rob-reynolds** [comment]
Resolved by https://github.com/DBCG/cql-evaluator/pull/123 and https://github.com/DBCG/cql-evaluator/pull/124
