### ISSUE TITLE
Update $care-gaps to include the SDE resources as Bundle entries

### ISSUE THREAD

**Issue by rob-reynolds** [DBCG/cqf-ruler#557]
SDE references have been re-designed.  $care-gaps needs to be updated.

IS: care-gaps adds resources referenced in evaluatedResource to the response bundle as entries, but does not add resources referenced by the http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData extension on the MR (new behavior).

SHOULD BE: add resources referenced by the http://hl7.org/fhir/us/davinci-deqm/StructureDefinition/extension-supplementalData extension.

Note, the bundle entries must remain unique.

**Comment by c-schuler** [comment]
Resolved in #567
