### ISSUE TITLE
$risk-adjustment missing evidence status date

### ISSUE THREAD

**Issue by rob-reynolds** [DBCG/cqf-ruler#571]
SDEs were updated in the Evaluator and the update caused the evidenceStatusDate extension in the MR group (https://github.com/DBCG/cqf-ruler/blob/760e2b5bedca4bacaa6248014cb5655e35b40ccc/plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/r4/RiskAdjustmentProvider.java#L39) to be missing.

IS: no evidenceStatusDate extension

SHOULD BE: there should be an evidenceStatusDate extension in the RA MR

Repro:  The issue can be reproduced by running Thunder Client tests in the RA IG (https://github.com/HL7/davinci-ra/) against the current version of the ruler:
- Thunder Client - Env - Risk Adjustment: set RAServer to the cqf ruler instance under test (usually http://localhost:8080/fhir/)
- Navigate to: Thunder Client - Collections - Risk Adjustment - $risk-adjustment Operation (STU2)
- initialize the server by running all the Config/Specification and Patient Data requests
- run any of the Evaluate <scenario> requests
- the resulting MeasureReport will not include the evidenceStatusDate extension

**Comment by c-schuler** [comment]
Resolved in #580
