### ISSUE TITLE
Improve Parameters utility type resolution

### ISSUE THREAD

**Issue by c-schuler** [DBCG/cqf-ruler#591]
Enhance the Parameters utility [`newPart`](https://github.com/DBCG/cqf-ruler/blob/master/core/src/main/java/org/opencds/cqf/ruler/utility/r4/Parameters.java#L43-L85) method with overload that determines the proper type given raw types (string, int, etc).

Current functionality:

```
Parameters params = newParameters(
     newPart("serviceDate", new DateType("2019-11-01")), 
     newPart("data", new StringType("this is the data")), 
     newPart("useServerData", new BooleanType(false)));
```

Example of desired functionality:

```
Parameters params = newParameters(
     newPart("serviceDate", "2019-11-01"), 
     newPart("data", "this is the data"), 
     newPart("useServerData", false));
```

**Comment by JPercival** [comment]
Resolved by #613
