### ISSUE TITLE
Recent docker images are not starting the server

### ISSUE THREAD

**Issue by magp18** [DBCG/cqf-ruler#595]
Hi, 

The three most recent docker images seem to be working for me, they build but the server doesn't start (error follows). The latest working is the 'mal' one from 4 months ago.
With the most recent ones I am getting: 
`[Flyway failed to initialize: none of the following migration scripts locations could be found: - classpath:db / migrations](https://stackoverflow.com/questions/68622431/flyway-failed-to-initialize-none-of-the-following-migration-scripts-locations-c)`

**Comment by c-schuler** [comment]
I have not been able to repro this issue. @magp18 are you using any custom configurations I should be aware of or is this an out-of-the-box build?

**Comment by magp18** [comment]
Thanks for pointing me to the configuration, that was the issue. Everything is working as expected now!
