### ISSUE TITLE
Library cbp-logic References DSTU2 Condition.dateRecorded Field

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#6]
Should probably be **assertedDate**. At least, when I make the change it works correctly. Here's a modified cbp measure with some more of the groups from the logic filled in.

Revised...
[cbp2.json.txt](https://github.com/DBCG/cqf-ruler/files/1174326/cbp2.json.txt)

**Comment by jeffeastman** [comment]
Here's an init bundle that may help. It adds blood pressure readings and hypertension to the COL patients.

[database-init.json.txt](https://github.com/DBCG/cqf-ruler/files/1174313/database-init.json.txt)

**Comment by c-schuler** [comment]
Thanks Jeff.

I changed that reference to assertedDate, updated the content in the init-bundle and pushed to the hapi server.

**Comment by jeffeastman** [comment]
You mean onsetDate, right?

**Comment by c-schuler** [comment]
No. onsetDate is in both dstu2 and stu3 Condition resources. dateRecorded was renamed assertedDate in stu3.

**Comment by jeffeastman** [comment]
Right, I figured that out and deleted my post. But here's a revised cbp2 with the Hx HTN statement removed because that evaluates to a Date and not a Boolean or Iterable, so it won't ever generate a count>0. I'm finally getting some traction on this stuff.

[cbp2.json.txt](https://github.com/DBCG/cqf-ruler/files/1174461/cbp2.json.txt)

**Comment by c-schuler** [comment]
Thanks again Jeff. Closing this...
