### ISSUE TITLE
Correct measure evaluation per scoring type

### ISSUE THREAD

**Issue by brynrhodes** [DBCG/cqf-ruler#60]
Measure evaluation does not always calculate according to the specifications for measure populations. Update the measure evaluator to use the calculations as specified [here](https://github.com/esacinc/CQL-Formatting-and-Usage-Wiki/wiki/Specifying-Population-Criteria).

**Comment by c-schuler** [comment]
Ah, I see. It doesn't account for multiple numerators and denominators within the same population. Perhaps the measure I am evaluating is improperly constructed (https://github.com/cqframework/hedis-ig/blob/master/resources/measure/measure-drr.json) ?

**Comment by brynrhodes** [comment]
That's correct, a proportion measure will only ever have one of each population criteria type within the same population group. Multiple populations within a measure are handled with multiple groups.
