### ISSUE TITLE
IPP Calculation Errors

### ISSUE THREAD

**Issue by jeffeastman** [DBCG/cqf-ruler#63]
When I evaluate the ASF measure against Aiden Michael Jones (age 0) the IPP comes back **true**. This is incorrect, because the IPP requires Aiden to be >= 18 years old.

```
Sending 'GET' request to URL: http://localhost:8080/cqf-ruler/baseDstu3/Measure/measure-asf/$evaluate-measure?patient=Patient-1137&periodStart=2017-1&periodEnd=2017-12&reportType=patient

Aiden Michael Jones [0]  (Patient-1137) is in initial-population
```

Investigating, it appears that the ExistsEvaluator localId=25 in the IPP expression is returning **true** when the _exists(operand)_ method is given the array `[ **false** ]`.

I'm not sure where the error actually is because the exists() method is pretty simple and the GreaterOrEqualEvaluator is correctly returning **false**.

This seems to occur in other measures too but I haven't characterized them to this level yet.

**Comment by jeffeastman** [comment]
More testing indicates the other measures ("asf", "bcs", "ccs", "col", "dms", "drr", "dsf", "pvs" ) aren't impacted by this.

**Comment by c-schuler** [comment]
Yeah, there was a bug in the CQL. I have fixed the CQL and updated the library in the [last commit](https://github.com/DBCG/cqf-ruler/blob/91d3aac9d6f725bf6a8911a2db3128c782bc5aad/src/test/resources/org/opencds/cqf/measure-evaluation/hedis-asf-bundle.json#L976-L1089).

**Comment by jeffeastman** [comment]
Did you update the hedis-ig project files too? Or, what's the best reference source for the various Measures and Libraries?

**Comment by c-schuler** [comment]
Unfortunately, the HEDIS IG is not building due to an issue with the publisher and npm package resolution. We have frozen commits to the repo while Grahame debugs the problem. For now, I am just updating the IG locally and will push everything once we're building again. For now, the best reference is the Ruler test suite.

**Comment by jeffeastman** [comment]
Ok. I pulled the cqf-ruler version and it looks better. I notice the library ids have changed from "measure-asf-logic" to "library-asf-logic". Has the Measure reference changed too?

**Comment by c-schuler** [comment]
Until the HEDIS IG is back up, yes. That IG is considered the "source of truth" for those resources.

The resource ids should be the same as what is in the hedis-ig. And they look to be the same (https://github.com/cqframework/hedis-ig/blob/master/resources/library/library-asf-logic.json) ... at least for ASF.

**Comment by jeffeastman** [comment]
I checked HEDIS IG and the measures still refer to "measure-xxx-logic" so I renamed the two from cqf-ruler and now the ASF IPP looks more reasonable. So closing this issue.

```
Measure = Measure/measure-asf
	denominator 2 = 15
	initial-population = 77
	numerator 2 = 15

```

**Comment by jeffeastman** [comment]
I just did a pull from the hedis-ig repo and copied all measures from GIT_REPO_PATH + "hedis-ig/resources/measure”

I even got a new one “measure-mrp.json” and it has 

  "library": [
    {
      "reference": "Library/measure-mrp-logic"
    }
  ],

**Comment by jeffeastman** [comment]
But the resources/libraries directory does have them all as library-xxx-logic so something’s not making sense.

Jeff

**Comment by c-schuler** [comment]
Huh. Not sure why we're seeing different things. I see the following in the [mrp measure](https://github.com/cqframework/hedis-ig/blob/master/resources/measure/measure-mrp.json#L34-L38):

"library": [
    {
      "reference": "Library/library-mrp-logic"
    }
  ],

**Comment by c-schuler** [comment]
Are you on the master branch?

**Comment by jeffeastman** [comment]
Yup

**Comment by c-schuler** [comment]
Well that's bizarre and frustrating... =/

**Comment by jeffeastman** [comment]
Aha, its my code thats doing the renaming!

**Comment by c-schuler** [comment]
Good to know I am not losing my mind. =)

**Comment by jeffeastman** [comment]
Now I’m worried about mine (-; Trying to recall why I had to do that so long ago...
