### ISSUE TITLE
Update cqf-ruler to hapi 6.1

### ISSUE THREAD

**Issue by Capt-Mac** [DBCG/cqf-ruler#630]
As a part of DQM-Platform: distributed-measure-eval work, developer requires use of HAPI-6.1 in order to leverage reduceStep for measure report aggregation

Acceptance Critieria:
cqf-ruler codebase is updated to the most recent version. Currently 6.1.1 as of the time of this writing.

**Comment by JPercival** [comment]
Here's the location:
https://github.com/DBCG/cqf-ruler/blob/master/pom.xml#L100
