### ISSUE TITLE
Update $davinci-ra.report operation to latest spec

### ISSUE THREAD

**Issue by rob-reynolds** [DBCG/cqf-ruler#639]
As a Payer, I need the MeasureReport/$davinci-ra.report operation implemented per the spec.

**DESCRIPTION:**

The Da Vinci Risk Adjustment IG (http://build.fhir.org/ig/HL7/davinci-ra/) has been updated to include the following stages:
- **Report Generation**
- Remediation
- Resolution

Additionally, Report Generation includes three options:
- Assisted
- **Self Generated**
- Evaluated

The $report operation of the CQF Ruler (https://github.com/DBCG/cqf-ruler/blob/74fd64d830d3675c82b38bb587fe8469b7d98696/plugin/ra/src/main/java/org/opencds/cqf/ruler/ra/r4/ReportProvider.java#L59) implements the Report Generation, Self Generated option.

The spec has been updated.  The CQF Ruler needs to be updated correspondingly.

**Changes:**

- [x]   update operation name to $davinci-ra.report

- [x]   update the API to the specification: http://build.fhir.org/ig/HL7/davinci-ra/OperationDefinition-davinci-ra.report.html, Parameters table:

![Image](https://user-images.githubusercontent.com/13257640/196061898-359b0636-cdbb-440f-a5ef-999e8b9b5861.png)

- [x]   update the functionality of the operation.  

The current implementation queries for Risk Adjustment Coding Gap Report Measure Reports and generates a result that is a [Risk Adjustment MeasureReport Bundle](http://build.fhir.org/ig/HL7/davinci-ra/StructureDefinition-ra-measurereport-bundle.html)

This needs to be updated to return a [Risk Adjustment Coding Gap Bundle](http://build.fhir.org/ig/HL7/davinci-ra/StructureDefinition-ra-coding-gap-bundle.html) instead.

The key differences are:
- bundle type = document
- first entry is a Composition
- there is a Original DetectedIssue (http://build.fhir.org/ig/HL7/davinci-ra/StructureDefinition-ra-coding-gap-original-detectedissue.html) bundle entry for each group (coding gap) in the RiskAdjustment MeasureReport
- the Composition.sections reference the above DetectedIssue resources
- the evidence.detail of the DetectedIssue resources references the same (evidence) resources as the MeasureReport evaluatedResources

![Image](https://user-images.githubusercontent.com/13257640/196062275-517905be-ff20-4754-b442-1466be3796cb.png)

Note, the spec is currently a work in progress so where the information above conflicts with the spec, the information above takes precedence.

**ACCEPTANCE CRITERIA:**

- [ ] the operation is named MeasureReport/$davinci-ra.report

- [ ] the API is:
![Image](https://user-images.githubusercontent.com/13257640/196061898-359b0636-cdbb-440f-a5ef-999e8b9b5861.png)

- [ ] Given a the ThunderClient Risk Adjustment Collection.Generate.$report.Config.ra-paramaters-standard request has been posted, the corresponding $report request returns a valid [Risk Adjustment Coding Gap Bundle](http://build.fhir.org/ig/HL7/davinci-ra/StructureDefinition-ra-coding-gap-bundle.html).

**Comment by JPercival** [comment]
Resolved by #651
