### ISSUE TITLE
MeasureReport.group object lacking required identifier

### ISSUE THREAD

**Issue by okeefm** [DBCG/cqf-ruler#67]
The `MeasureReport` object generated by the server as a result of running the `$evaluate-measure` operation is missing an `identifier` on each `group` object embedded within it. This is causing it to fail profile validation when the `$validate` operation is called on it.

**Comment by c-schuler** [comment]
Thanks @okeefm! I will address this oversight shortly.

**Comment by okeefm** [comment]
Tested during Connectathon 20, and the server is now returning `identifier`s for each `group` object. Closing this issue as resolved.
