### ISSUE TITLE
Running $evaluate-measure with a reportType of 'patient-list' does not return any results, even for queries known to give results

### ISSUE THREAD

**Issue by okeefm** [DBCG/cqf-ruler#68]
If you run the `$evaluate-measure` operation on a measurement period that should return non-zero counts, but add the `patient-list` `reportType`, all the population counts are zeroed out.

Example query: `http://measure.eval.kanvix.com/cqf-ruler/baseDstu3/Measure/measure-bcs/$evaluate-measure?periodStart=1997-01-01&periodEnd=1997-12-31` will return non-zero results for the 3 populations

`http://measure.eval.kanvix.com/cqf-ruler/baseDstu3/Measure/measure-bcs/$evaluate-measure?periodStart=1997-01-01&periodEnd=1997-12-31&reportType=patient-list` will return zeroed results for the 3 populations

@jlordoyne is also seeing this issue.

**Comment by c-schuler** [comment]
Specify the practitioner. For example:
`http://measure.eval.kanvix.com/cqf-ruler/baseDstu3/Measure/measure-bcs/$evaluate-measure?periodStart=1997-01-01&periodEnd=1997-12-31&reportType=patient-list&practitioner=Practitioner-2520`

**Comment by okeefm** [comment]
I tested this out, and it does work if you specify a practitioner. Is that an intended requirement of the system?

**Comment by c-schuler** [comment]
Yes it was. That requirement has since been removed.

**Comment by okeefm** [comment]
Tested this during Connectathon 20, and `$evaluate-measure` with a `reportType` of `patient-list` no longer requires a practitioner to get results. Closing the issue as resolved.
