### ISSUE TITLE
adding 'user' to validation of medication-prescribe context 

### ISSUE THREAD

**Issue by rkboyce** [DBCG/cqf-ruler#70]
Hi, at the Connectathon there was a change to put the 'user' attribute within the medication-prescribe context. This change was put out to the CDS sandbox and cqf-ruler needs a small change to enable validation of requests with this change:

line 35 of src/main/java/org/opencds/cqf/cdshooks/request/MedicationPrescribeContext.java 

Current:
```
src/main/java/org/opencds/cqf/cdshooks/request/MedicationPrescribeContext.java {
```
Suggested change:

```
if (!key.equals("patientId") && !key.equals("encounterId") && !key.equals("medications") && !key.equals("user")) {
```

**Comment by c-schuler** [comment]
Thank you for the feedback @rkboyce! I will be updating the CDS Hooks implementation, including this issue, shortly.

**Comment by c-schuler** [comment]
@rkboyce: is there some documentation explaining the justification for this change? I don't see it in the CDS Hooks docs anywhere.
