### ISSUE TITLE
Authorization header not being passed in FHIR execution call

### ISSUE THREAD

**Issue by pz12** [DBCG/cqf-ruler#74]
I work for the company that maintains the HSPC Sandbox application. The Sandbox has two ways of performing FHIR calls to the server: secured and open. When a CQF call (i.e. $submit-data) is performed to an open endpoint, it works just fine. However, it's not working on our secured endpoints and here's why. As part of a call to a secured endpoint, an "Authorization" header is included. We use a Bearer token (i.e. BEARER ei392mnix...) in that header to hold the authorization token given by our auth server, granting the user permission to perform the FHIR query. But using the CQF ruler, that token isn't passed on to the actual transaction and therefore access is denied. 

Here's an example of how we've been able to pass the header on to a transaction call:

IGenericClient client = this.getContext().newRestfulGenericClient(details.getFhirServerBase());
        if (details.getHeader("Authorization") != null) {
            String[] splitAuth = details.getHeader("Authorization").split(" ");
            String token = splitAuth[1];
            BearerTokenAuthInterceptor authInterceptor = new BearerTokenAuthInterceptor(token);
            client.registerInterceptor(authInterceptor);
        }
return client.transaction().withBundle(transactionBundle).execute();

Is there any way something similar could be implemented in the endpoints found in the cqf-ruler?

**Comment by c-schuler** [comment]
@pz12: I have implemented this interceptor for the $submit-data operation and deployed to the measure.eval.kanvix.com/cqf-ruler/baseDstu3 endpoint.

Please test and let me know if it works. Thanks!

**Comment by pz12** [comment]
@c-schuler Is this implemented in the actual code or just this endpoint? I can't seem to get it to work on our system.

**Comment by c-schuler** [comment]
@pz12: It is in the code. You can see the commit with the code above (
https://github.com/DBCG/cqf-ruler/commit/0f278824c39525411afe3806a7f91e06c488fe2b). The code hasn't been merged to master yet. It is in the [config-update](https://github.com/DBCG/cqf-ruler/tree/config-update) branch.

**Comment by pz12** [comment]
Great! Could we also have the same functionality in all of the endpoints ($evaluate-measure, $care-gaps, $apply, $data-requirements) cqf-ruler provides?

**Comment by pz12** [comment]
Has there been any progress on my past request?

**Comment by c-schuler** [comment]
Apologies...
The $submit-data operation is the only operation that uses the HAPI client. Did you ever get the $submit-data operation working in the sandbox?

**Comment by pz12** [comment]
I'm actually getting a NullPointerException on that call with or without authorization whereas it was working without authorization before.

**Comment by pz12** [comment]
I'm also getting this error sometimes: "HTTP 301 Moved Permanently"

**Comment by c-schuler** [comment]
Ok, 0.1.6-SNAPSHOT is published.
Please refer to issue #76 for possible deployment issues using with Tomcat.
