### ISSUE TITLE
0.1.5-SNAPSHOT plugin causing errors with our Bundle calls

### ISSUE THREAD

**Issue by pz12** [DBCG/cqf-ruler#78]
When using version 0.1.4-SNAPSHOT, we did not have this issue. After upgrading our plugin to 0.1.5-SNAPSHOT, our FHIR server started experiencing strange behavior. When a resource call was made that returned a bundle (image 1) over an HTTPS secured connection, all of the embedded urls were given in HTTP unsecured urls (image 2), giving us errors (image 3). What's causing this and could you look into it?

Thank you for your time.
<img width="739" alt="screen shot 2018-11-01 at 7 23 51 am" src="https://user-images.githubusercontent.com/21222506/47856065-e4a58900-ddab-11e8-9d2f-d680f9d1e303.png">
<img width="967" alt="screen shot 2018-11-01 at 7 24 06 am" src="https://user-images.githubusercontent.com/21222506/47856064-e4a58900-ddab-11e8-8490-f8a0e3d24051.png">
<img width="1576" alt="screen shot 2018-11-01 at 7 27 02 am" src="https://user-images.githubusercontent.com/21222506/47856063-e4a58900-ddab-11e8-8194-b2d76c075b0e.png">

**Comment by pz12** [comment]
This is still an issue in 0.1.6-SNAPSHOT.

**Comment by pz12** [comment]
This is what it should look like:
<img width="1042" alt="screen shot 2018-11-08 at 8 29 47 am" src="https://user-images.githubusercontent.com/21222506/48208639-83902f00-e330-11e8-8d22-ccffecc6111b.png">

**Comment by c-schuler** [comment]
Apologies for the late reply... Is this still an issue?

**Comment by pz12** [comment]
No it's not, you resolved it in a later release.
