### ISSUE TITLE
Unexpected results for $evaluate-measure

### ISSUE THREAD

**Issue by tstrass** [DBCG/cqf-ruler#84]
Looking at measure with ID `measure-col` ([FHIR](http://measure.eval.kanvix.com/cqf-ruler/baseDstu3/Measure/measure-col), [ECQI](https://ecqi.healthit.gov/system/files/ecqm/measures/CMS130v7.htm)), I am seeing unexpected results from measure evaluation.

Calling http://measure.eval.kanvix.com/cqf-ruler/baseDstu3/Measure/measure-col/$evaluate-measure?periodStart=2018&periodEnd=2018&reportType=patient-list responds with a MeasureReport that names 124 patients in the IPOP and in the denominator. I don't think this can be possible, because as of right now there are only 66 Encounters on stored on the server in total. And looking at the measure logic, it seems an Encounter during the measure period is a requirement for IPOP.

Looking more closely at a single patient example (http://measure.eval.kanvix.com/cqf-ruler/baseDstu3/Measure/measure-col/$evaluate-measure?periodStart=2018&periodEnd=2018&reportType=patient&patient=Patient-6483), this measure report says this patient is in the IPOP, but I am unable to find any Encounters or even any other resources linked to this patient.

Just as a side note for posterity, the reason I'm looking into this is because I am trying to grab fixtures that I can use in a TestScript for the `$submit-data` and `$evaluate-measure` endpoints.

**Comment by brynrhodes** [comment]
@tstrass , thank you  for the report, we have fixed several issues in the run up to the connectathon, so I think this issue may have already been addressed, running the measure for 2018 gives 38 denominator, 0 numerator, and Patient-6483 is not in the initial population or denominator for this measure.

**Comment by mgramigna** [comment]
@brynrhodes I did some investigating and it looks like this issue was indeed addressed in the latest of `cqf-ruler`. Thanks!

**Comment by c-schuler** [comment]
Looks like this has been resolved... Closing.
