### ISSUE TITLE
R4 Claim creation "Use" code issue

### ISSUE THREAD

**Issue by okeefm** [DBCG/cqf-ruler#89]
When trying to upload a `Bundle` to the R4 `cqf-ruler` endpoint, I get a `400` error:

`POST` http://measure.eval.kanvix.com/cqf-ruler/baseR4
Payload:
```
{
    "resourceType": "Bundle",
    "type": "transaction",
    "entry": [
        {
            "fullUrl": "urn:uuid:79f09de0-d511-41cd-9a1a-ebe7f534a09c",
            "resource": {
                "resourceType": "Claim",
                "id": "79f09de0-d511-41cd-9a1a-ebe7f534a09c",
                "status": "active",
                "use": "claim"
            }
        }
    ]
}
```

Response: 
```
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Invalid attribute value \"claim\": Unknown Use code 'claim'</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Invalid attribute value \"claim\": Unknown Use code 'claim'"
        }
    ]
}
```

I tried this same POST request against the HAPI R4 instance (http://hapi.fhir.org/baseR4), and was successful. `claim` is a valid code in the [Claim Use Valueset](https://www.hl7.org/fhir/valueset-claim-use.html) for the [R4 Claim Resource](https://www.hl7.org/fhir/claim.html)

**Comment by c-schuler** [comment]
This is happening because the Ruler is currently using HAPI 3.5, which doesn't fully support R4 like HAPI 3.7, which is what the HAPI instance is using. Making this an enhancement request to migrate to HAPI 3.7. Thank you =).

**Comment by JPercival** [comment]
Latest version of the ruler supports R4.
