### ISSUE TITLE
ensure value sets with urn oid prefix work

### ISSUE THREAD

**Issue by duncand** [DBCG/cqf-ruler#9]
Officially a valueset referenced in terms of an oid should typically be declared with the prefix "urn:oid:" before the number sequence.  The task of this ticket is to ensure that the CQF Ruler accepts CQL value set declarations with this prefix and handles them intelligently, so users can write to this best practice and not have to worry if an implementation otherwise requires the prefix to be absent or present.

**Comment by c-schuler** [comment]
Closing this.
