### ISSUE TITLE
dependency error:

### ISSUE THREAD

**Issue by AjeeshPillai** [DBCG/cqf-ruler#93]
We tried to build the cqf-ruler code in eclipse we are getting the dependency error:
![test](https://user-images.githubusercontent.com/47226076/52485925-f0ad9d80-2b87-11e9-9b8d-786bff68d0f0.png)

We tried to update the project in maven, but the below to dependency jar files are not available. 
![test1](https://user-images.githubusercontent.com/47226076/52485979-133fb680-2b88-11e9-940f-be8d2181319d.png)
cql-engine-1.2.51-SNAPSHOT.jar
cql-engine-fhir-1.2.51-SNAPSHOT.jar
The available version is 1.2.20 but we are unable to use this version as we are getting errors.

Can we get the cql-engine-1.2.51-SNAPSHOT.jar & cql-engine-fhir-1.2.51-SNAPSHOT.jar files.

**Comment by c-schuler** [comment]
What version of Maven are you using?
